final infoPokemons = [
  {
    "obtido": false,
    "code": "A1001",
    "nome": "Bulbasaur",
    "buster": "Mewtwo",
    "raridade": "🔹",
    "chance_1_3": 2.000,
    "chance_4": 0.00,
    "chance_5": 0.00,
    "MEW": true,
    "promoA": false,
  },
  {
    "obtido": false,
    "code": "A1002",
    "nome": "Ivysaur",
    "buster": "Mewtwo",
    "raridade": "🔹🔹",
    "chance_1_3": 0.00,
    "chance_4": 2.571,
    "chance_5": 1.714,
    "MEW": true,
    "promoA": false,
  },
  {
    "obtido": false,
    "code": "A1003",
    "nome": "Venusaur",
    "buster": "Mewtwo",
    "raridade": "🔹🔹🔹",
    "chance_1_3": 0.00,
    "chance_4": 0.357,
    "chance_5": 1.429,
    "MEW": true,
    "promoA": false,
  },
  {
    "obtido": false,
    "code": "A1004",
    "nome": "Venusaur ex",
    "buster": "Mewtwo",
    "raridade": "🔹🔹🔹🔹",
    "chance_1_3": 0.00,
    "chance_4": 0.333,
    "chance_5": 1.333,
    "MEW": false,
    "promoA": false,
  },
  {
    "obtido": false,
    "code": "A1005",
    "nome": "Caterpie",
    "buster": "Pikachu",
    "raridade": "🔹",
    "chance_1_3": 2.000,
    "chance_4": 0.00,
    "chance_5": 0.00,
    "MEW": true,
    "promoA": false,
  },
  {
    "obtido": false,
    "code": "A1006",
    "nome": "Metapod",
    "buster": "Pikachu",
    "raridade": "🔹",
    "chance_1_3": 2.000,
    "chance_4": 0.00,
    "chance_5": 0.00,
    "MEW": true,
    "promoA": false,
  },
  {
    "obtido": false,
    "code": "A1007",
    "nome": "Butterfree",
    "buster": "Pikachu",
    "raridade": "🔹🔹🔹",
    "chance_1_3": 0.00,
    "chance_4": 0.357,
    "chance_5": 1.429,
    "MEW": true,
    "promoA": false,
  },
  {
    "obtido": false,
    "code": "A1008",
    "nome": "Weedle",
    "buster": "Mewtwo",
    "raridade": "🔹",
    "chance_1_3": 2.000,
    "chance_4": 0.00,
    "chance_5": 0.00,
    "MEW": true,
    "promoA": false,
  },
  {
    "obtido": false,
    "code": "A1009",
    "nome": "Kakuna",
    "buster": "Mewtwo",
    "raridade": "🔹",
    "chance_1_3": 2.000,
    "chance_4": 0.00,
    "chance_5": 0.00,
    "MEW": true,
    "promoA": false,
  },
  {
    "obtido": false,
    "code": "A1010",
    "nome": "Beedrill",
    "buster": "Mewtwo",
    "raridade": "🔹🔹🔹",
    "chance_1_3": 0.00,
    "chance_4": 0.357,
    "chance_5": 1.429,
    "MEW": true,
    "promoA": false,
  },
  {
    "obtido": false,
    "code": "A1011",
    "nome": "Oddish",
    "buster": "Charizard",
    "raridade": "🔹",
    "chance_1_3": 2.000,
    "chance_4": 0.00,
    "chance_5": 0.00,
    "MEW": true,
    "promoA": false,
  },
  {
    "obtido": false,
    "code": "A1012",
    "nome": "Gloom",
    "buster": "Charizard",
    "raridade": "🔹🔹",
    "chance_1_3": 0.00,
    "chance_4": 2.571,
    "chance_5": 1.714,
    "MEW": true,
    "promoA": false,
  },
  {
    "obtido": false,
    "code": "A1013",
    "nome": "Vileplume",
    "buster": "Charizard",
    "raridade": "🔹🔹🔹",
    "chance_1_3": 0.00,
    "chance_4": 0.357,
    "chance_5": 1.429,
    "MEW": true,
    "promoA": false,
  },
  {
    "obtido": false,
    "code": "A1014",
    "nome": "Paras",
    "buster": "Pikachu",
    "raridade": "🔹",
    "chance_1_3": 2.000,
    "chance_4": 0.00,
    "chance_5": 0.00,
    "MEW": true,
    "promoA": false,
  },
  {
    "obtido": false,
    "code": "A1015",
    "nome": "Parasect",
    "buster": "Pikachu",
    "raridade": "🔹🔹",
    "chance_1_3": 0.00,
    "chance_4": 2.571,
    "chance_5": 1.714,
    "MEW": true,
    "promoA": false,
  },
  {
    "obtido": false,
    "code": "A1016",
    "nome": "Venonat",
    "buster": "Mewtwo",
    "raridade": "🔹",
    "chance_1_3": 2.000,
    "chance_4": 0.00,
    "chance_5": 0.00,
    "MEW": true,
    "promoA": false,
  },
  {
    "obtido": false,
    "code": "A1017",
    "nome": "Venomoth",
    "buster": "Mewtwo",
    "raridade": "🔹🔹",
    "chance_1_3": 0.00,
    "chance_4": 2.571,
    "chance_5": 1.714,
    "MEW": true,
    "promoA": false,
  },
  {
    "obtido": false,
    "code": "A1018",
    "nome": "Bellsprout",
    "buster": "Charizard",
    "raridade": "🔹",
    "chance_1_3": 2.000,
    "chance_4": 0.00,
    "chance_5": 0.00,
    "MEW": true,
    "promoA": false,
  },
  {
    "obtido": false,
    "code": "A1019",
    "nome": "Weepinbell",
    "buster": "Charizard",
    "raridade": "🔹🔹",
    "chance_1_3": 0.00,
    "chance_4": 2.571,
    "chance_5": 1.714,
    "MEW": true,
    "promoA": false,
  },
  {
    "obtido": false,
    "code": "A1020",
    "nome": "Victreebel",
    "buster": "Charizard",
    "raridade": "🔹🔹🔹",
    "chance_1_3": 0.00,
    "chance_4": 0.357,
    "chance_5": 1.429,
    "MEW": true,
    "promoA": false,
  },
  {
    "obtido": false,
    "code": "A1021",
    "nome": "Exeggcute",
    "buster": "Charizard",
    "raridade": "🔹",
    "chance_1_3": 2.000,
    "chance_4": 0.00,
    "chance_5": 0.00,
    "MEW": true,
    "promoA": false,
  },
  {
    "obtido": false,
    "code": "A1022",
    "nome": "Exeggutor",
    "buster": "Charizard",
    "raridade": "🔹🔹🔹",
    "chance_1_3": 0.00,
    "chance_4": 0.357,
    "chance_5": 1.429,
    "MEW": true,
    "promoA": false,
  },
  {
    "obtido": false,
    "code": "A1023",
    "nome": "Exeggutor ex",
    "buster": "Charizard",
    "raridade": "🔹🔹🔹🔹",
    "chance_1_3": 0.00,
    "chance_4": 0.333,
    "chance_5": 1.333,
    "MEW": false,
    "promoA": false,
  },
  {
    "obtido": false,
    "code": "A1024",
    "nome": "Tangela",
    "buster": "Charizard",
    "raridade": "🔹",
    "chance_1_3": 2.000,
    "chance_4": 0.00,
    "chance_5": 0.00,
    "MEW": true,
    "promoA": false,
  },
  {
    "obtido": false,
    "code": "A1025",
    "nome": "Scyther",
    "buster": "Mewtwo",
    "raridade": "🔹",
    "chance_1_3": 2.000,
    "chance_4": 0.00,
    "chance_5": 0.00,
    "MEW": true,
    "promoA": false,
  },
  {
    "obtido": false,
    "code": "A1026",
    "nome": "Pinsir",
    "buster": "All",
    "raridade": "🔹🔹",
    "chance_1_3": 0.00,
    "chance_4": 2.571,
    "chance_5": 1.714,
    "MEW": true,
    "promoA": false,
  },
  {
    "obtido": false,
    "code": "A1027",
    "nome": "Cottonee",
    "buster": "All",
    "raridade": "🔹",
    "chance_1_3": 2.000,
    "chance_4": 0.00,
    "chance_5": 0.00,
    "MEW": false,
    "promoA": false,
  },
  {
    "obtido": false,
    "code": "A1028",
    "nome": "Whimsicott",
    "buster": "All",
    "raridade": "🔹🔹",
    "chance_1_3": 0.00,
    "chance_4": 2.571,
    "chance_5": 1.714,
    "MEW": false,
    "promoA": false,
  },
  {
    "obtido": false,
    "code": "A1029",
    "nome": "Petilil",
    "buster": "All",
    "raridade": "🔹",
    "chance_1_3": 2.000,
    "chance_4": 0.00,
    "chance_5": 0.00,
    "MEW": false,
    "promoA": false,
  },
  {
    "obtido": false,
    "code": "A1030",
    "nome": "Lilligant",
    "buster": "All",
    "raridade": "🔹🔹",
    "chance_1_3": 0.00,
    "chance_4": 2.571,
    "chance_5": 1.714,
    "MEW": false,
    "promoA": false,
  },
  {
    "obtido": false,
    "code": "A1031",
    "nome": "Skiddo",
    "buster": "Charizard",
    "raridade": "🔹",
    "chance_1_3": 2.000,
    "chance_4": 0.00,
    "chance_5": 0.00,
    "MEW": false,
    "promoA": false,
  },
  {
    "obtido": false,
    "code": "A1032",
    "nome": "Gogoat",
    "buster": "Charizard",
    "raridade": "🔹",
    "chance_1_3": 2.000,
    "chance_4": 0.00,
    "chance_5": 0.00,
    "MEW": false,
    "promoA": false,
  },
  {
    "obtido": false,
    "code": "A1033",
    "nome": "Charmander",
    "buster": "Charizard",
    "raridade": "🔹",
    "chance_1_3": 2.000,
    "chance_4": 0.00,
    "chance_5": 0.00,
    "MEW": true,
    "promoA": false,
  },
  {
    "obtido": false,
    "code": "A1034",
    "nome": "Charmeleon",
    "buster": "Charizard",
    "raridade": "🔹🔹",
    "chance_1_3": 0.00,
    "chance_4": 2.571,
    "chance_5": 1.714,
    "MEW": true,
    "promoA": false,
  },
  {
    "obtido": false,
    "code": "A1035",
    "nome": "Charizard",
    "buster": "Charizard",
    "raridade": "🔹🔹🔹",
    "chance_1_3": 0.00,
    "chance_4": 0.357,
    "chance_5": 1.429,
    "MEW": true,
    "promoA": false,
  },
  {
    "obtido": false,
    "code": "A1036",
    "nome": "Charizard ex",
    "buster": "Charizard",
    "raridade": "🔹🔹🔹🔹",
    "chance_1_3": 0.00,
    "chance_4": 0.333,
    "chance_5": 1.333,
    "MEW": false,
    "promoA": false,
  },
  {
    "obtido": false,
    "code": "A1037",
    "nome": "Vulpix",
    "buster": "Charizard",
    "raridade": "🔹",
    "chance_1_3": 2.000,
    "chance_4": 0.00,
    "chance_5": 0.00,
    "MEW": true,
    "promoA": false,
  },
  {
    "obtido": false,
    "code": "A1038",
    "nome": "Ninetales",
    "buster": "Charizard",
    "raridade": "🔹🔹",
    "chance_1_3": 0.00,
    "chance_4": 2.571,
    "chance_5": 1.714,
    "MEW": true,
    "promoA": false,
  },
  {
    "obtido": false,
    "code": "A1039",
    "nome": "Growlithe",
    "buster": "Pikachu",
    "raridade": "🔹",
    "chance_1_3": 2.000,
    "chance_4": 0.00,
    "chance_5": 0.00,
    "MEW": true,
    "promoA": false,
  },
  {
    "obtido": false,
    "code": "A1040",
    "nome": "Arcanine",
    "buster": "Pikachu",
    "raridade": "🔹🔹🔹",
    "chance_1_3": 0.00,
    "chance_4": 0.357,
    "chance_5": 1.429,
    "MEW": true,
    "promoA": false,
  },
  {
    "obtido": false,
    "code": "A1041",
    "nome": "Arcanine ex",
    "buster": "Pikachu",
    "raridade": "🔹🔹🔹🔹",
    "chance_1_3": 0.00,
    "chance_4": 0.333,
    "chance_5": 1.333,
    "MEW": false,
    "promoA": false,
  },
  {
    "obtido": false,
    "code": "A1042",
    "nome": "Ponyta",
    "buster": "All",
    "raridade": "🔹",
    "chance_1_3": 2.000,
    "chance_4": 0.00,
    "chance_5": 0.00,
    "MEW": true,
    "promoA": false,
  },
  {
    "obtido": false,
    "code": "A1043",
    "nome": "Rapidash",
    "buster": "All",
    "raridade": "🔹🔹",
    "chance_1_3": 0.00,
    "chance_4": 2.571,
    "chance_5": 1.714,
    "MEW": true,
    "promoA": false,
  },
  {
    "obtido": false,
    "code": "A1044",
    "nome": "Magmar",
    "buster": "Charizard",
    "raridade": "🔹",
    "chance_1_3": 2.000,
    "chance_4": 0.00,
    "chance_5": 0.00,
    "MEW": true,
    "promoA": false,
  },
  {
    "obtido": false,
    "code": "A1045",
    "nome": "Flareon",
    "buster": "Charizard",
    "raridade": "🔹🔹🔹",
    "chance_1_3": 0.00,
    "chance_4": 0.357,
    "chance_5": 1.429,
    "MEW": true,
    "promoA": false,
  },
  {
    "obtido": false,
    "code": "A1046",
    "nome": "Moltres",
    "buster": "Charizard",
    "raridade": "🔹🔹🔹",
    "chance_1_3": 0.00,
    "chance_4": 0.357,
    "chance_5": 1.429,
    "MEW": true,
    "promoA": false,
  },
  {
    "obtido": false,
    "code": "A1047",
    "nome": "Moltres ex",
    "buster": "Charizard",
    "raridade": "🔹🔹🔹🔹",
    "chance_1_3": 0.00,
    "chance_4": 0.333,
    "chance_5": 1.333,
    "MEW": false,
    "promoA": false,
  },
  {
    "obtido": false,
    "code": "A1048",
    "nome": "Heatmor",
    "buster": "All",
    "raridade": "🔹",
    "chance_1_3": 2.000,
    "chance_4": 0.00,
    "chance_5": 0.00,
    "MEW": false,
    "promoA": false,
  },
  {
    "obtido": false,
    "code": "A1049",
    "nome": "Salandit",
    "buster": "Mewtwo",
    "raridade": "🔹",
    "chance_1_3": 2.000,
    "chance_4": 0.00,
    "chance_5": 0.00,
    "MEW": false,
    "promoA": false,
  },
  {
    "obtido": false,
    "code": "A1050",
    "nome": "Salazzle",
    "buster": "Mewtwo",
    "raridade": "🔹",
    "chance_1_3": 2.000,
    "chance_4": 0.00,
    "chance_5": 0.00,
    "MEW": false,
    "promoA": false,
  },
  {
    "obtido": false,
    "code": "A1051",
    "nome": "Sizzlipede",
    "buster": "All",
    "raridade": "🔹",
    "chance_1_3": 2.000,
    "chance_4": 0.00,
    "chance_5": 0.00,
    "MEW": false,
    "promoA": false,
  },
  {
    "obtido": false,
    "code": "A1052",
    "nome": "Centiskorch",
    "buster": "All",
    "raridade": "🔹🔹",
    "chance_1_3": 0.00,
    "chance_4": 2.571,
    "chance_5": 1.714,
    "MEW": false,
    "promoA": false,
  },
  {
    "obtido": false,
    "code": "A1053",
    "nome": "Squirtle",
    "buster": "Pikachu",
    "raridade": "🔹",
    "chance_1_3": 2.000,
    "chance_4": 0.00,
    "chance_5": 0.00,
    "MEW": true,
    "promoA": false,
  },
  {
    "obtido": false,
    "code": "A1054",
    "nome": "Wartortle",
    "buster": "Pikachu",
    "raridade": "🔹🔹",
    "chance_1_3": 0.00,
    "chance_4": 2.571,
    "chance_5": 1.714,
    "MEW": true,
    "promoA": false,
  },
  {
    "obtido": false,
    "code": "A1055",
    "nome": "Blastoise",
    "buster": "Pikachu",
    "raridade": "🔹🔹🔹",
    "chance_1_3": 0.00,
    "chance_4": 0.357,
    "chance_5": 1.429,
    "MEW": true,
    "promoA": false,
  },
  {
    "obtido": false,
    "code": "A1056",
    "nome": "Blastoise ex",
    "buster": "Pikachu",
    "raridade": "🔹🔹🔹🔹",
    "chance_1_3": 0.00,
    "chance_4": 0.333,
    "chance_5": 1.333,
    "MEW": false,
    "promoA": false,
  },
  {
    "obtido": false,
    "code": "A1057",
    "nome": "Psyduck",
    "buster": "All",
    "raridade": "🔹",
    "chance_1_3": 2.000,
    "chance_4": 0.00,
    "chance_5": 0.00,
    "MEW": true,
    "promoA": false,
  },
  {
    "obtido": false,
    "code": "A1058",
    "nome": "Golduck",
    "buster": "All",
    "raridade": "🔹🔹",
    "chance_1_3": 0.00,
    "chance_4": 2.571,
    "chance_5": 1.714,
    "MEW": true,
    "promoA": false,
  },
  {
    "obtido": false,
    "code": "A1059",
    "nome": "Poliwag",
    "buster": "Charizard",
    "raridade": "🔹",
    "chance_1_3": 2.000,
    "chance_4": 0.00,
    "chance_5": 0.00,
    "MEW": true,
    "promoA": false,
  },
  {
    "obtido": false,
    "code": "A1060",
    "nome": "Poliwhirl",
    "buster": "Charizard",
    "raridade": "🔹🔹",
    "chance_1_3": 0.00,
    "chance_4": 2.571,
    "chance_5": 1.714,
    "MEW": true,
    "promoA": false,
  },
  {
    "obtido": false,
    "code": "A1061",
    "nome": "Poliwrath",
    "buster": "Charizard",
    "raridade": "🔹🔹🔹",
    "chance_1_3": 0.00,
    "chance_4": 0.357,
    "chance_5": 1.429,
    "MEW": true,
    "promoA": false,
  },
  {
    "obtido": false,
    "code": "A1062",
    "nome": "Tentacool",
    "buster": "Mewtwo",
    "raridade": "🔹",
    "chance_1_3": 2.000,
    "chance_4": 0.00,
    "chance_5": 0.00,
    "MEW": true,
    "promoA": false,
  },
  {
    "obtido": false,
    "code": "A1063",
    "nome": "Tentacruel",
    "buster": "Mewtwo",
    "raridade": "🔹🔹",
    "chance_1_3": 0.00,
    "chance_4": 2.571,
    "chance_5": 1.714,
    "MEW": true,
    "promoA": false,
  },
  {
    "obtido": false,
    "code": "A1064",
    "nome": "Seel",
    "buster": "Pikachu",
    "raridade": "🔹",
    "chance_1_3": 2.000,
    "chance_4": 0.00,
    "chance_5": 0.00,
    "MEW": true,
    "promoA": false,
  },
  {
    "obtido": false,
    "code": "A1065",
    "nome": "Dewgong",
    "buster": "Pikachu",
    "raridade": "🔹🔹",
    "chance_1_3": 0.00,
    "chance_4": 2.571,
    "chance_5": 1.714,
    "MEW": true,
    "promoA": false,
  },
  {
    "obtido": false,
    "code": "A1066",
    "nome": "Shellder",
    "buster": "Mewtwo",
    "raridade": "🔹",
    "chance_1_3": 2.000,
    "chance_4": 0.00,
    "chance_5": 0.00,
    "MEW": true,
    "promoA": false,
  },
  {
    "obtido": false,
    "code": "A1067",
    "nome": "Cloyster",
    "buster": "Mewtwo",
    "raridade": "🔹🔹",
    "chance_1_3": 0.00,
    "chance_4": 2.571,
    "chance_5": 1.714,
    "MEW": true,
    "promoA": false,
  },
  {
    "obtido": false,
    "code": "A1068",
    "nome": "Krabby",
    "buster": "Mewtwo",
    "raridade": "🔹",
    "chance_1_3": 2.000,
    "chance_4": 0.00,
    "chance_5": 0.00,
    "MEW": true,
    "promoA": false,
  },
  {
    "obtido": false,
    "code": "A1069",
    "nome": "Kingler",
    "buster": "Mewtwo",
    "raridade": "🔹🔹",
    "chance_1_3": 0.00,
    "chance_4": 2.571,
    "chance_5": 1.714,
    "MEW": true,
    "promoA": false,
  },
  {
    "obtido": false,
    "code": "A1070",
    "nome": "Horsea",
    "buster": "Pikachu",
    "raridade": "🔹",
    "chance_1_3": 2.000,
    "chance_4": 0.00,
    "chance_5": 0.00,
    "MEW": true,
    "promoA": false,
  },
  {
    "obtido": false,
    "code": "A1071",
    "nome": "Seadra",
    "buster": "Pikachu",
    "raridade": "🔹🔹",
    "chance_1_3": 0.00,
    "chance_4": 2.571,
    "chance_5": 1.714,
    "MEW": true,
    "promoA": false,
  },
  {
    "obtido": false,
    "code": "A1072",
    "nome": "Goldeen",
    "buster": "Pikachu",
    "raridade": "🔹",
    "chance_1_3": 2.000,
    "chance_4": 0.00,
    "chance_5": 0.00,
    "MEW": true,
    "promoA": false,
  },
  {
    "obtido": false,
    "code": "A1073",
    "nome": "Seaking",
    "buster": "Pikachu",
    "raridade": "🔹",
    "chance_1_3": 2.000,
    "chance_4": 0.00,
    "chance_5": 0.00,
    "MEW": true,
    "promoA": false,
  },
  {
    "obtido": false,
    "code": "A1074",
    "nome": "Staryu",
    "buster": "Charizard",
    "raridade": "🔹",
    "chance_1_3": 2.000,
    "chance_4": 0.00,
    "chance_5": 0.00,
    "MEW": true,
    "promoA": false,
  },
  {
    "obtido": false,
    "code": "A1075",
    "nome": "Starmie",
    "buster": "Charizard",
    "raridade": "🔹🔹",
    "chance_1_3": 0.00,
    "chance_4": 2.571,
    "chance_5": 1.714,
    "MEW": true,
    "promoA": false,
  },
  {
    "obtido": false,
    "code": "A1076",
    "nome": "Starmie ex",
    "buster": "Charizard",
    "raridade": "🔹🔹🔹🔹",
    "chance_1_3": 0.00,
    "chance_4": 0.333,
    "chance_5": 1.333,
    "MEW": false,
    "promoA": false,
  },
  {
    "obtido": false,
    "code": "A1077",
    "nome": "Magikarp",
    "buster": "Pikachu",
    "raridade": "🔹",
    "chance_1_3": 2.000,
    "chance_4": 0.00,
    "chance_5": 0.00,
    "MEW": true,
    "promoA": false,
  },
  {
    "obtido": false,
    "code": "A1078",
    "nome": "Gyarados",
    "buster": "Pikachu",
    "raridade": "🔹🔹🔹",
    "chance_1_3": 0.00,
    "chance_4": 0.357,
    "chance_5": 1.429,
    "MEW": true,
    "promoA": false,
  },
  {
    "obtido": false,
    "code": "A1079",
    "nome": "Lapras",
    "buster": "Charizard",
    "raridade": "🔹🔹🔹",
    "chance_1_3": 0.00,
    "chance_4": 0.357,
    "chance_5": 1.429,
    "MEW": true,
    "promoA": false,
  },
  {
    "obtido": false,
    "code": "A1080",
    "nome": "Vaporeon",
    "buster": "Mewtwo",
    "raridade": "🔹🔹🔹",
    "chance_1_3": 0.00,
    "chance_4": 0.357,
    "chance_5": 1.429,
    "MEW": true,
    "promoA": false,
  },
  {
    "obtido": false,
    "code": "A1081",
    "nome": "Omanyte",
    "buster": "Pikachu",
    "raridade": "🔹🔹",
    "chance_1_3": 0.00,
    "chance_4": 2.571,
    "chance_5": 1.714,
    "MEW": true,
    "promoA": false,
  },
  {
    "obtido": false,
    "code": "A1082",
    "nome": "Omastar",
    "buster": "Pikachu",
    "raridade": "🔹🔹🔹",
    "chance_1_3": 0.00,
    "chance_4": 0.357,
    "chance_5": 1.429,
    "MEW": true,
    "promoA": false,
  },
  {
    "obtido": false,
    "code": "A1083",
    "nome": "Articuno",
    "buster": "Mewtwo",
    "raridade": "🔹🔹🔹",
    "chance_1_3": 0.00,
    "chance_4": 0.357,
    "chance_5": 1.429,
    "MEW": true,
    "promoA": false,
  },
  {
    "obtido": false,
    "code": "A1084",
    "nome": "Articuno ex",
    "buster": "Mewtwo",
    "raridade": "🔹🔹🔹🔹",
    "chance_1_3": 0.00,
    "chance_4": 0.333,
    "chance_5": 1.333,
    "MEW": false,
    "promoA": false,
  },
  {
    "obtido": false,
    "code": "A1085",
    "nome": "Ducklett",
    "buster": "Charizard",
    "raridade": "🔹",
    "chance_1_3": 2.000,
    "chance_4": 0.00,
    "chance_5": 0.00,
    "MEW": false,
    "promoA": false,
  },
  {
    "obtido": false,
    "code": "A1086",
    "nome": "Swanna",
    "buster": "Charizard",
    "raridade": "🔹🔹",
    "chance_1_3": 0.00,
    "chance_4": 2.571,
    "chance_5": 1.714,
    "MEW": false,
    "promoA": false,
  },
  {
    "obtido": false,
    "code": "A1087",
    "nome": "Froakie",
    "buster": "Charizard",
    "raridade": "🔹",
    "chance_1_3": 2.000,
    "chance_4": 0.00,
    "chance_5": 0.00,
    "MEW": false,
    "promoA": false,
  },
  {
    "obtido": false,
    "code": "A1088",
    "nome": "Frogadier",
    "buster": "Charizard",
    "raridade": "🔹🔹",
    "chance_1_3": 0.00,
    "chance_4": 2.571,
    "chance_5": 1.714,
    "MEW": false,
    "promoA": false,
  },
  {
    "obtido": false,
    "code": "A1089",
    "nome": "Greninja",
    "buster": "Charizard",
    "raridade": "🔹🔹🔹",
    "chance_1_3": 0.00,
    "chance_4": 0.357,
    "chance_5": 1.429,
    "MEW": false,
    "promoA": false,
  },
  {
    "obtido": false,
    "code": "A1090",
    "nome": "Pyukumuku",
    "buster": "Charizard",
    "raridade": "🔹",
    "chance_1_3": 2.000,
    "chance_4": 0.00,
    "chance_5": 0.00,
    "MEW": false,
    "promoA": false,
  },
  {
    "obtido": false,
    "code": "A1091",
    "nome": "Bruxish",
    "buster": "All",
    "raridade": "🔹🔹",
    "chance_1_3": 0.00,
    "chance_4": 2.571,
    "chance_5": 1.714,
    "MEW": false,
    "promoA": false,
  },
  {
    "obtido": false,
    "code": "A1092",
    "nome": "Snom",
    "buster": "All",
    "raridade": "🔹",
    "chance_1_3": 2.000,
    "chance_4": 0.00,
    "chance_5": 0.00,
    "MEW": false,
    "promoA": false,
  },
  {
    "obtido": false,
    "code": "A1093",
    "nome": "Frosmoth",
    "buster": "All",
    "raridade": "🔹🔹",
    "chance_1_3": 0.00,
    "chance_4": 2.571,
    "chance_5": 1.714,
    "MEW": false,
    "promoA": false,
  },
  {
    "obtido": false,
    "code": "A1094",
    "nome": "Pikachu",
    "buster": "Pikachu",
    "raridade": "🔹",
    "chance_1_3": 2.000,
    "chance_4": 0.00,
    "chance_5": 0.00,
    "MEW": true,
    "promoA": false,
  },
  {
    "obtido": false,
    "code": "A1095",
    "nome": "Raichu",
    "buster": "Pikachu",
    "raridade": "🔹🔹🔹",
    "chance_1_3": 0.00,
    "chance_4": 0.357,
    "chance_5": 1.429,
    "MEW": true,
    "promoA": false,
  },
  {
    "obtido": false,
    "code": "A1096",
    "nome": "Pikachu ex",
    "buster": "Pikachu",
    "raridade": "🔹🔹🔹🔹",
    "chance_1_3": 0.00,
    "chance_4": 0.333,
    "chance_5": 1.333,
    "MEW": false,
    "promoA": false,
  },
  {
    "obtido": false,
    "code": "A1097",
    "nome": "Magnemite",
    "buster": "Pikachu",
    "raridade": "🔹",
    "chance_1_3": 2.000,
    "chance_4": 0.00,
    "chance_5": 0.00,
    "MEW": true,
    "promoA": false,
  },
  {
    "obtido": false,
    "code": "A1098",
    "nome": "Magneton",
    "buster": "Pikachu",
    "raridade": "🔹🔹🔹",
    "chance_1_3": 0.00,
    "chance_4": 0.357,
    "chance_5": 1.429,
    "MEW": true,
    "promoA": false,
  },
  {
    "obtido": false,
    "code": "A1099",
    "nome": "Voltorb",
    "buster": "Pikachu",
    "raridade": "🔹",
    "chance_1_3": 2.000,
    "chance_4": 0.00,
    "chance_5": 0.00,
    "MEW": true,
    "promoA": false,
  },
  {
    "obtido": false,
    "code": "A1100",
    "nome": "Electrode",
    "buster": "Pikachu",
    "raridade": "🔹🔹",
    "chance_1_3": 0.00,
    "chance_4": 2.571,
    "chance_5": 1.714,
    "MEW": true,
    "promoA": false,
  },
  {
    "obtido": false,
    "code": "A1101",
    "nome": "Electabuzz",
    "buster": "Pikachu",
    "raridade": "🔹",
    "chance_1_3": 2.000,
    "chance_4": 0.00,
    "chance_5": 0.00,
    "MEW": true,
    "promoA": false,
  },
  {
    "obtido": false,
    "code": "A1102",
    "nome": "Jolteon",
    "buster": "Pikachu",
    "raridade": "🔹🔹🔹",
    "chance_1_3": 0.00,
    "chance_4": 0.357,
    "chance_5": 1.429,
    "MEW": true,
    "promoA": false,
  },
  {
    "obtido": false,
    "code": "A1103",
    "nome": "Zapdos",
    "buster": "Pikachu",
    "raridade": "🔹🔹🔹",
    "chance_1_3": 0.00,
    "chance_4": 0.357,
    "chance_5": 1.429,
    "MEW": true,
    "promoA": false,
  },
  {
    "obtido": false,
    "code": "A1104",
    "nome": "Zapdos ex",
    "buster": "Pikachu",
    "raridade": "🔹🔹🔹🔹",
    "chance_1_3": 0.00,
    "chance_4": 0.333,
    "chance_5": 1.333,
    "MEW": false,
    "promoA": false,
  },
  {
    "obtido": false,
    "code": "A1105",
    "nome": "Blitzle",
    "buster": "All",
    "raridade": "🔹",
    "chance_1_3": 2.000,
    "chance_4": 0.00,
    "chance_5": 0.00,
    "MEW": false,
    "promoA": false,
  },
  {
    "obtido": false,
    "code": "A1106",
    "nome": "Zebstrika",
    "buster": "All",
    "raridade": "🔹🔹",
    "chance_1_3": 0.00,
    "chance_4": 2.571,
    "chance_5": 1.714,
    "MEW": false,
    "promoA": false,
  },
  {
    "obtido": false,
    "code": "A1107",
    "nome": "Tynamo",
    "buster": "Mewtwo",
    "raridade": "🔹",
    "chance_1_3": 2.000,
    "chance_4": 0.00,
    "chance_5": 0.00,
    "MEW": false,
    "promoA": false,
  },
  {
    "obtido": false,
    "code": "A1108",
    "nome": "Eelektrik",
    "buster": "Mewtwo",
    "raridade": "🔹🔹",
    "chance_1_3": 0.00,
    "chance_4": 2.571,
    "chance_5": 1.714,
    "MEW": false,
    "promoA": false,
  },
  {
    "obtido": false,
    "code": "A1109",
    "nome": "Eelektross",
    "buster": "Mewtwo",
    "raridade": "🔹🔹🔹",
    "chance_1_3": 0.00,
    "chance_4": 0.357,
    "chance_5": 1.429,
    "MEW": false,
    "promoA": false,
  },
  {
    "obtido": false,
    "code": "A1110",
    "nome": "Helioptile",
    "buster": "All",
    "raridade": "🔹",
    "chance_1_3": 2.000,
    "chance_4": 0.00,
    "chance_5": 0.00,
    "MEW": false,
    "promoA": false,
  },
  {
    "obtido": false,
    "code": "A1111",
    "nome": "Heliolisk",
    "buster": "All",
    "raridade": "🔹",
    "chance_1_3": 2.000,
    "chance_4": 0.00,
    "chance_5": 0.00,
    "MEW": false,
    "promoA": false,
  },
  {
    "obtido": false,
    "code": "A1112",
    "nome": "Pincurchin",
    "buster": "All",
    "raridade": "🔹🔹",
    "chance_1_3": 0.00,
    "chance_4": 2.571,
    "chance_5": 1.714,
    "MEW": false,
    "promoA": false,
  },
  {
    "obtido": false,
    "code": "A1113",
    "nome": "Clefairy",
    "buster": "Pikachu",
    "raridade": "🔹",
    "chance_1_3": 2.000,
    "chance_4": 0.00,
    "chance_5": 0.00,
    "MEW": true,
    "promoA": false,
  },
  {
    "obtido": false,
    "code": "A1114",
    "nome": "Clefable",
    "buster": "Pikachu",
    "raridade": "🔹🔹",
    "chance_1_3": 0.00,
    "chance_4": 2.571,
    "chance_5": 1.714,
    "MEW": true,
    "promoA": false,
  },
  {
    "obtido": false,
    "code": "A1115",
    "nome": "Abra",
    "buster": "Charizard",
    "raridade": "🔹",
    "chance_1_3": 2.000,
    "chance_4": 0.00,
    "chance_5": 0.00,
    "MEW": true,
    "promoA": false,
  },
  {
    "obtido": false,
    "code": "A1116",
    "nome": "Kadabra",
    "buster": "Charizard",
    "raridade": "🔹🔹",
    "chance_1_3": 0.00,
    "chance_4": 2.571,
    "chance_5": 1.714,
    "MEW": true,
    "promoA": false,
  },
  {
    "obtido": false,
    "code": "A1117",
    "nome": "Alakazam",
    "buster": "Charizard",
    "raridade": "🔹🔹🔹",
    "chance_1_3": 0.00,
    "chance_4": 0.357,
    "chance_5": 1.429,
    "MEW": true,
    "promoA": false,
  },
  {
    "obtido": false,
    "code": "A1118",
    "nome": "Slowpoke",
    "buster": "All",
    "raridade": "🔹",
    "chance_1_3": 2.000,
    "chance_4": 0.00,
    "chance_5": 0.00,
    "MEW": true,
    "promoA": false,
  },
  {
    "obtido": false,
    "code": "A1119",
    "nome": "Slowbro",
    "buster": "All",
    "raridade": "🔹🔹",
    "chance_1_3": 0.00,
    "chance_4": 2.571,
    "chance_5": 1.714,
    "MEW": true,
    "promoA": false,
  },
  {
    "obtido": false,
    "code": "A1120",
    "nome": "Gastly",
    "buster": "Mewtwo",
    "raridade": "🔹",
    "chance_1_3": 2.000,
    "chance_4": 0.00,
    "chance_5": 0.00,
    "MEW": true,
    "promoA": false,
  },
  {
    "obtido": false,
    "code": "A1121",
    "nome": "Haunter",
    "buster": "Mewtwo",
    "raridade": "🔹🔹",
    "chance_1_3": 0.00,
    "chance_4": 2.571,
    "chance_5": 1.714,
    "MEW": true,
    "promoA": false,
  },
  {
    "obtido": false,
    "code": "A1122",
    "nome": "Gengar",
    "buster": "Mewtwo",
    "raridade": "🔹🔹🔹",
    "chance_1_3": 0.00,
    "chance_4": 0.357,
    "chance_5": 1.429,
    "MEW": true,
    "promoA": false,
  },
  {
    "obtido": false,
    "code": "A1123",
    "nome": "Gengar ex",
    "buster": "Mewtwo",
    "raridade": "🔹🔹🔹🔹",
    "chance_1_3": 0.00,
    "chance_4": 0.333,
    "chance_5": 1.333,
    "MEW": false,
    "promoA": false,
  },
  {
    "obtido": false,
    "code": "A1124",
    "nome": "Drowzee",
    "buster": "Pikachu",
    "raridade": "🔹",
    "chance_1_3": 2.000,
    "chance_4": 0.00,
    "chance_5": 0.00,
    "MEW": true,
    "promoA": false,
  },
  {
    "obtido": false,
    "code": "A1125",
    "nome": "Hypno",
    "buster": "Pikachu",
    "raridade": "🔹🔹🔹",
    "chance_1_3": 0.00,
    "chance_4": 0.357,
    "chance_5": 1.429,
    "MEW": true,
    "promoA": false,
  },
  {
    "obtido": false,
    "code": "A1126",
    "nome": "Mr.Mime",
    "buster": "Mewtwo",
    "raridade": "🔹🔹",
    "chance_1_3": 0.00,
    "chance_4": 2.571,
    "chance_5": 1.714,
    "MEW": true,
    "promoA": false,
  },
  {
    "obtido": false,
    "code": "A1127",
    "nome": "Jynx",
    "buster": "Mewtwo",
    "raridade": "🔹",
    "chance_1_3": 2.000,
    "chance_4": 0.00,
    "chance_5": 0.00,
    "MEW": true,
    "promoA": false,
  },
  {
    "obtido": false,
    "code": "A1128",
    "nome": "Mewtwo",
    "buster": "Mewtwo",
    "raridade": "🔹🔹🔹",
    "chance_1_3": 0.00,
    "chance_4": 0.357,
    "chance_5": 1.429,
    "MEW": true,
    "promoA": false,
  },
  {
    "obtido": false,
    "code": "A1129",
    "nome": "Mewtwo ex",
    "buster": "Mewtwo",
    "raridade": "🔹🔹🔹🔹",
    "chance_1_3": 0.00,
    "chance_4": 0.333,
    "chance_5": 1.333,
    "MEW": false,
    "promoA": false,
  },
  {
    "obtido": false,
    "code": "A1130",
    "nome": "Ralts",
    "buster": "Mewtwo",
    "raridade": "🔹",
    "chance_1_3": 2.000,
    "chance_4": 0.00,
    "chance_5": 0.00,
    "MEW": false,
    "promoA": false,
  },
  {
    "obtido": false,
    "code": "A1131",
    "nome": "Kirlia",
    "buster": "Mewtwo",
    "raridade": "🔹🔹",
    "chance_1_3": 0.00,
    "chance_4": 2.571,
    "chance_5": 1.714,
    "MEW": false,
    "promoA": false,
  },
  {
    "obtido": false,
    "code": "A1132",
    "nome": "Gardevoir",
    "buster": "Mewtwo",
    "raridade": "🔹🔹🔹",
    "chance_1_3": 0.00,
    "chance_4": 0.357,
    "chance_5": 1.429,
    "MEW": false,
    "promoA": false,
  },
  {
    "obtido": false,
    "code": "A1133",
    "nome": "Woobat",
    "buster": "All",
    "raridade": "🔹",
    "chance_1_3": 2.000,
    "chance_4": 0.00,
    "chance_5": 0.00,
    "MEW": false,
    "promoA": false,
  },
  {
    "obtido": false,
    "code": "A1134",
    "nome": "Swoobat",
    "buster": "All",
    "raridade": "🔹",
    "chance_1_3": 2.000,
    "chance_4": 0.00,
    "chance_5": 0.00,
    "MEW": false,
    "promoA": false,
  },
  {
    "obtido": false,
    "code": "A1135",
    "nome": "Golett",
    "buster": "All",
    "raridade": "🔹",
    "chance_1_3": 2.000,
    "chance_4": 0.00,
    "chance_5": 0.00,
    "MEW": false,
    "promoA": false,
  },
  {
    "obtido": false,
    "code": "A1136",
    "nome": "Golurk",
    "buster": "All",
    "raridade": "🔹🔹",
    "chance_1_3": 0.00,
    "chance_4": 2.571,
    "chance_5": 1.714,
    "MEW": false,
    "promoA": false,
  },
  {
    "obtido": false,
    "code": "A1137",
    "nome": "Sandshrew",
    "buster": "All",
    "raridade": "🔹",
    "chance_1_3": 2.000,
    "chance_4": 0.00,
    "chance_5": 0.00,
    "MEW": true,
    "promoA": false,
  },
  {
    "obtido": false,
    "code": "A1138",
    "nome": "Sandslash",
    "buster": "All",
    "raridade": "🔹🔹",
    "chance_1_3": 0.00,
    "chance_4": 2.571,
    "chance_5": 1.714,
    "MEW": true,
    "promoA": false,
  },
  {
    "obtido": false,
    "code": "A1139",
    "nome": "Diglett",
    "buster": "Pikachu",
    "raridade": "🔹",
    "chance_1_3": 2.000,
    "chance_4": 0.00,
    "chance_5": 0.00,
    "MEW": true,
    "promoA": false,
  },
  {
    "obtido": false,
    "code": "A1140",
    "nome": "Dugtrio",
    "buster": "Pikachu",
    "raridade": "🔹🔹",
    "chance_1_3": 0.00,
    "chance_4": 2.571,
    "chance_5": 1.714,
    "MEW": true,
    "promoA": false,
  },
  {
    "obtido": false,
    "code": "A1141",
    "nome": "Mankey",
    "buster": "Charizard",
    "raridade": "🔹",
    "chance_1_3": 2.000,
    "chance_4": 0.00,
    "chance_5": 0.00,
    "MEW": true,
    "promoA": false,
  },
  {
    "obtido": false,
    "code": "A1142",
    "nome": "Primeape",
    "buster": "Charizard",
    "raridade": "🔹🔹",
    "chance_1_3": 0.00,
    "chance_4": 2.571,
    "chance_5": 1.714,
    "MEW": true,
    "promoA": false,
  },
  {
    "obtido": false,
    "code": "A1143",
    "nome": "Machop",
    "buster": "Charizard",
    "raridade": "🔹",
    "chance_1_3": 2.000,
    "chance_4": 0.00,
    "chance_5": 0.00,
    "MEW": true,
    "promoA": false,
  },
  {
    "obtido": false,
    "code": "A1144",
    "nome": "Machoke",
    "buster": "Charizard",
    "raridade": "🔹🔹",
    "chance_1_3": 0.00,
    "chance_4": 2.571,
    "chance_5": 1.714,
    "MEW": true,
    "promoA": false,
  },
  {
    "obtido": false,
    "code": "A1145",
    "nome": "Machamp",
    "buster": "Charizard",
    "raridade": "🔹🔹🔹",
    "chance_1_3": 0.00,
    "chance_4": 0.357,
    "chance_5": 1.429,
    "MEW": true,
    "promoA": false,
  },
  {
    "obtido": false,
    "code": "A1146",
    "nome": "Machamp ex",
    "buster": "Charizard",
    "raridade": "🔹🔹🔹🔹",
    "chance_1_3": 0.00,
    "chance_4": 0.333,
    "chance_5": 1.333,
    "MEW": false,
    "promoA": false,
  },
  {
    "obtido": false,
    "code": "A1147",
    "nome": "Geodude",
    "buster": "Pikachu",
    "raridade": "🔹",
    "chance_1_3": 2.000,
    "chance_4": 0.00,
    "chance_5": 0.00,
    "MEW": true,
    "promoA": false,
  },
  {
    "obtido": false,
    "code": "A1148",
    "nome": "Graveler",
    "buster": "Pikachu",
    "raridade": "🔹🔹",
    "chance_1_3": 0.00,
    "chance_4": 2.571,
    "chance_5": 1.714,
    "MEW": true,
    "promoA": false,
  },
  {
    "obtido": false,
    "code": "A1149",
    "nome": "Golem",
    "buster": "Pikachu",
    "raridade": "🔹🔹🔹",
    "chance_1_3": 0.00,
    "chance_4": 0.357,
    "chance_5": 1.429,
    "MEW": true,
    "promoA": false,
  },
  {
    "obtido": false,
    "code": "A1150",
    "nome": "Onix",
    "buster": "Pikachu",
    "raridade": "🔹🔹",
    "chance_1_3": 0.00,
    "chance_4": 2.571,
    "chance_5": 1.714,
    "MEW": true,
    "promoA": false,
  },
  {
    "obtido": false,
    "code": "A1151",
    "nome": "Cubone",
    "buster": "Mewtwo",
    "raridade": "🔹",
    "chance_1_3": 2.000,
    "chance_4": 0.00,
    "chance_5": 0.00,
    "MEW": true,
    "promoA": false,
  },
  {
    "obtido": false,
    "code": "A1152",
    "nome": "Marowak",
    "buster": "Mewtwo",
    "raridade": "🔹🔹",
    "chance_1_3": 0.00,
    "chance_4": 2.571,
    "chance_5": 1.714,
    "MEW": true,
    "promoA": false,
  },
  {
    "obtido": false,
    "code": "A1153",
    "nome": "Marowak ex",
    "buster": "Mewtwo",
    "raridade": "🔹🔹🔹🔹",
    "chance_1_3": 0.00,
    "chance_4": 0.333,
    "chance_5": 1.333,
    "MEW": false,
    "promoA": false,
  },
  {
    "obtido": false,
    "code": "A1154",
    "nome": "Hitmonlee",
    "buster": "Mewtwo",
    "raridade": "🔹",
    "chance_1_3": 2.000,
    "chance_4": 0.00,
    "chance_5": 0.00,
    "MEW": true,
    "promoA": false,
  },
  {
    "obtido": false,
    "code": "A1155",
    "nome": "Hitmonchan",
    "buster": "Charizard",
    "raridade": "🔹",
    "chance_1_3": 2.000,
    "chance_4": 0.00,
    "chance_5": 0.00,
    "MEW": true,
    "promoA": false,
  },
  {
    "obtido": false,
    "code": "A1156",
    "nome": "Rhyhorn",
    "buster": "Mewtwo",
    "raridade": "🔹",
    "chance_1_3": 2.000,
    "chance_4": 0.00,
    "chance_5": 0.00,
    "MEW": true,
    "promoA": false,
  },
  {
    "obtido": false,
    "code": "A1157",
    "nome": "Rhydon",
    "buster": "Mewtwo",
    "raridade": "🔹🔹",
    "chance_1_3": 0.00,
    "chance_4": 2.571,
    "chance_5": 1.714,
    "MEW": true,
    "promoA": false,
  },
  {
    "obtido": false,
    "code": "A1158",
    "nome": "Kabuto",
    "buster": "Charizard",
    "raridade": "🔹🔹",
    "chance_1_3": 0.00,
    "chance_4": 2.571,
    "chance_5": 1.714,
    "MEW": true,
    "promoA": false,
  },
  {
    "obtido": false,
    "code": "A1159",
    "nome": "Kabutops",
    "buster": "Charizard",
    "raridade": "🔹🔹🔹",
    "chance_1_3": 0.00,
    "chance_4": 0.357,
    "chance_5": 1.429,
    "MEW": true,
    "promoA": false,
  },
  {
    "obtido": false,
    "code": "A1160",
    "nome": "Mienfoo",
    "buster": "Pikachu",
    "raridade": "🔹",
    "chance_1_3": 2.000,
    "chance_4": 0.00,
    "chance_5": 0.00,
    "MEW": false,
    "promoA": false,
  },
  {
    "obtido": false,
    "code": "A1161",
    "nome": "Mienshao",
    "buster": "Pikachu",
    "raridade": "🔹🔹",
    "chance_1_3": 0.00,
    "chance_4": 2.571,
    "chance_5": 1.714,
    "MEW": false,
    "promoA": false,
  },
  {
    "obtido": false,
    "code": "A1162",
    "nome": "Clobbopus",
    "buster": "All",
    "raridade": "🔹",
    "chance_1_3": 2.000,
    "chance_4": 0.00,
    "chance_5": 0.00,
    "MEW": false,
    "promoA": false,
  },
  {
    "obtido": false,
    "code": "A1163",
    "nome": "Grapploct",
    "buster": "All",
    "raridade": "🔹🔹",
    "chance_1_3": 0.00,
    "chance_4": 2.571,
    "chance_5": 1.714,
    "MEW": false,
    "promoA": false,
  },
  {
    "obtido": false,
    "code": "A1164",
    "nome": "Ekans",
    "buster": "All",
    "raridade": "🔹",
    "chance_1_3": 2.000,
    "chance_4": 0.00,
    "chance_5": 0.00,
    "MEW": true,
    "promoA": false,
  },
  {
    "obtido": false,
    "code": "A1165",
    "nome": "Arbok",
    "buster": "All",
    "raridade": "🔹🔹",
    "chance_1_3": 0.00,
    "chance_4": 2.571,
    "chance_5": 1.714,
    "MEW": true,
    "promoA": false,
  },
  {
    "obtido": false,
    "code": "A1166",
    "nome": "Nidoran♀",
    "buster": "Pikachu",
    "raridade": "🔹",
    "chance_1_3": 2.000,
    "chance_4": 0.00,
    "chance_5": 0.00,
    "MEW": true,
    "promoA": false,
  },
  {
    "obtido": false,
    "code": "A1167",
    "nome": "Nidorina",
    "buster": "Pikachu",
    "raridade": "🔹🔹",
    "chance_1_3": 0.00,
    "chance_4": 2.571,
    "chance_5": 1.714,
    "MEW": true,
    "promoA": false,
  },
  {
    "obtido": false,
    "code": "A1168",
    "nome": "Nidoqueen",
    "buster": "Pikachu",
    "raridade": "🔹🔹🔹",
    "chance_1_3": 0.00,
    "chance_4": 0.357,
    "chance_5": 1.429,
    "MEW": true,
    "promoA": false,
  },
  {
    "obtido": false,
    "code": "A1169",
    "nome": "Nidoran♂",
    "buster": "Pikachu",
    "raridade": "🔹",
    "chance_1_3": 2.000,
    "chance_4": 0.00,
    "chance_5": 0.00,
    "MEW": true,
    "promoA": false,
  },
  {
    "obtido": false,
    "code": "A1170",
    "nome": "Nidorino",
    "buster": "Pikachu",
    "raridade": "🔹🔹",
    "chance_1_3": 0.00,
    "chance_4": 2.571,
    "chance_5": 1.714,
    "MEW": true,
    "promoA": false,
  },
  {
    "obtido": false,
    "code": "A1171",
    "nome": "Nidoking",
    "buster": "Pikachu",
    "raridade": "🔹🔹🔹",
    "chance_1_3": 0.00,
    "chance_4": 0.357,
    "chance_5": 1.429,
    "MEW": true,
    "promoA": false,
  },
  {
    "obtido": false,
    "code": "A1172",
    "nome": "Zubat",
    "buster": "Mewtwo",
    "raridade": "🔹",
    "chance_1_3": 2.000,
    "chance_4": 0.00,
    "chance_5": 0.00,
    "MEW": true,
    "promoA": false,
  },
  {
    "obtido": false,
    "code": "A1173",
    "nome": "Golbat",
    "buster": "Mewtwo",
    "raridade": "🔹🔹",
    "chance_1_3": 0.00,
    "chance_4": 2.571,
    "chance_5": 1.714,
    "MEW": true,
    "promoA": false,
  },
  {
    "obtido": false,
    "code": "A1174",
    "nome": "Grimer",
    "buster": "Mewtwo",
    "raridade": "🔹",
    "chance_1_3": 2.000,
    "chance_4": 0.00,
    "chance_5": 0.00,
    "MEW": true,
    "promoA": false,
  },
  {
    "obtido": false,
    "code": "A1175",
    "nome": "Muk",
    "buster": "Mewtwo",
    "raridade": "🔹🔹🔹",
    "chance_1_3": 0.00,
    "chance_4": 0.357,
    "chance_5": 1.429,
    "MEW": true,
    "promoA": false,
  },
  {
    "obtido": false,
    "code": "A1176",
    "nome": "Koffing",
    "buster": "Mewtwo",
    "raridade": "🔹",
    "chance_1_3": 2.000,
    "chance_4": 0.00,
    "chance_5": 0.00,
    "MEW": true,
    "promoA": false,
  },
  {
    "obtido": false,
    "code": "A1177",
    "nome": "Weezing",
    "buster": "Mewtwo",
    "raridade": "🔹🔹🔹",
    "chance_1_3": 0.00,
    "chance_4": 0.357,
    "chance_5": 1.429,
    "MEW": true,
    "promoA": false,
  },
  {
    "obtido": false,
    "code": "A1178",
    "nome": "Mawile",
    "buster": "Charizard",
    "raridade": "🔹",
    "chance_1_3": 2.000,
    "chance_4": 0.00,
    "chance_5": 0.00,
    "MEW": false,
    "promoA": false,
  },
  {
    "obtido": false,
    "code": "A1179",
    "nome": "Pawniard",
    "buster": "All",
    "raridade": "🔹",
    "chance_1_3": 2.000,
    "chance_4": 0.00,
    "chance_5": 0.00,
    "MEW": false,
    "promoA": false,
  },
  {
    "obtido": false,
    "code": "A1180",
    "nome": "Bisharp",
    "buster": "All",
    "raridade": "🔹🔹",
    "chance_1_3": 0.00,
    "chance_4": 2.571,
    "chance_5": 1.714,
    "MEW": false,
    "promoA": false,
  },
  {
    "obtido": false,
    "code": "A1181",
    "nome": "Meltan",
    "buster": "Charizard",
    "raridade": "🔹",
    "chance_1_3": 2.000,
    "chance_4": 0.00,
    "chance_5": 0.00,
    "MEW": false,
    "promoA": false,
  },
  {
    "obtido": false,
    "code": "A1182",
    "nome": "Melmetal",
    "buster": "Charizard",
    "raridade": "🔹🔹🔹",
    "chance_1_3": 0.00,
    "chance_4": 0.357,
    "chance_5": 1.429,
    "MEW": false,
    "promoA": false,
  },
  {
    "obtido": false,
    "code": "A1183",
    "nome": "Dratini",
    "buster": "Mewtwo",
    "raridade": "🔹",
    "chance_1_3": 2.000,
    "chance_4": 0.00,
    "chance_5": 0.00,
    "MEW": true,
    "promoA": false,
  },
  {
    "obtido": false,
    "code": "A1184",
    "nome": "Dragonair",
    "buster": "Mewtwo",
    "raridade": "🔹🔹",
    "chance_1_3": 0.00,
    "chance_4": 2.571,
    "chance_5": 1.714,
    "MEW": true,
    "promoA": false,
  },
  {
    "obtido": false,
    "code": "A1185",
    "nome": "Dragonite",
    "buster": "Mewtwo",
    "raridade": "🔹🔹🔹",
    "chance_1_3": 0.00,
    "chance_4": 0.357,
    "chance_5": 1.429,
    "MEW": true,
    "promoA": false,
  },
  {
    "obtido": false,
    "code": "A1186",
    "nome": "Pidgey",
    "buster": "Mewtwo",
    "raridade": "🔹",
    "chance_1_3": 2.000,
    "chance_4": 0.00,
    "chance_5": 0.00,
    "MEW": true,
    "promoA": false,
  },
  {
    "obtido": false,
    "code": "A1187",
    "nome": "Pidgeotto",
    "buster": "Mewtwo",
    "raridade": "🔹",
    "chance_1_3": 2.000,
    "chance_4": 0.00,
    "chance_5": 0.00,
    "MEW": true,
    "promoA": false,
  },
  {
    "obtido": false,
    "code": "A1188",
    "nome": "Pidgeot",
    "buster": "Mewtwo",
    "raridade": "🔹🔹🔹",
    "chance_1_3": 0.00,
    "chance_4": 0.357,
    "chance_5": 1.429,
    "MEW": true,
    "promoA": false,
  },
  {
    "obtido": false,
    "code": "A1189",
    "nome": "Rattata",
    "buster": "All",
    "raridade": "🔹",
    "chance_1_3": 2.000,
    "chance_4": 0.00,
    "chance_5": 0.00,
    "MEW": true,
    "promoA": false,
  },
  {
    "obtido": false,
    "code": "A1190",
    "nome": "Raticate",
    "buster": "All",
    "raridade": "🔹",
    "chance_1_3": 2.000,
    "chance_4": 0.00,
    "chance_5": 0.00,
    "MEW": true,
    "promoA": false,
  },
  {
    "obtido": false,
    "code": "A1191",
    "nome": "Spearow",
    "buster": "Charizard",
    "raridade": "🔹",
    "chance_1_3": 2.000,
    "chance_4": 0.00,
    "chance_5": 0.00,
    "MEW": true,
    "promoA": false,
  },
  {
    "obtido": false,
    "code": "A1192",
    "nome": "Fearow",
    "buster": "Charizard",
    "raridade": "🔹",
    "chance_1_3": 2.000,
    "chance_4": 0.00,
    "chance_5": 0.00,
    "MEW": true,
    "promoA": false,
  },
  {
    "obtido": false,
    "code": "A1193",
    "nome": "Jigglypuff",
    "buster": "Pikachu",
    "raridade": "🔹",
    "chance_1_3": 2.000,
    "chance_4": 0.00,
    "chance_5": 0.00,
    "MEW": true,
    "promoA": false,
  },
  {
    "obtido": false,
    "code": "A1194",
    "nome": "Wigglytuff",
    "buster": "Pikachu",
    "raridade": "🔹",
    "chance_1_3": 2.000,
    "chance_4": 0.00,
    "chance_5": 0.00,
    "MEW": true,
    "promoA": false,
  },
  {
    "obtido": false,
    "code": "A1195",
    "nome": "Wigglytuff ex",
    "buster": "Pikachu",
    "raridade": "🔹🔹🔹🔹",
    "chance_1_3": 0.00,
    "chance_4": 0.333,
    "chance_5": 1.333,
    "MEW": false,
    "promoA": false,
  },
  {
    "obtido": false,
    "code": "A1196",
    "nome": "Meowth",
    "buster": "Charizard",
    "raridade": "🔹",
    "chance_1_3": 2.000,
    "chance_4": 0.00,
    "chance_5": 0.00,
    "MEW": true,
    "promoA": false,
  },
  {
    "obtido": false,
    "code": "A1197",
    "nome": "Persian",
    "buster": "Charizard",
    "raridade": "🔹🔹",
    "chance_1_3": 0.00,
    "chance_4": 2.571,
    "chance_5": 1.714,
    "MEW": true,
    "promoA": false,
  },
  {
    "obtido": false,
    "code": "A1198",
    "nome": "Farfetchd",
    "buster": "All",
    "raridade": "🔹",
    "chance_1_3": 2.000,
    "chance_4": 0.00,
    "chance_5": 0.00,
    "MEW": true,
    "promoA": false,
  },
  {
    "obtido": false,
    "code": "A1199",
    "nome": "Doduo",
    "buster": "All",
    "raridade": "🔹",
    "chance_1_3": 2.000,
    "chance_4": 0.00,
    "chance_5": 0.00,
    "MEW": true,
    "promoA": false,
  },
  {
    "obtido": false,
    "code": "A1200",
    "nome": "Dodrio",
    "buster": "All",
    "raridade": "🔹🔹",
    "chance_1_3": 0.00,
    "chance_4": 2.571,
    "chance_5": 1.714,
    "MEW": true,
    "promoA": false,
  },
  {
    "obtido": false,
    "code": "A1201",
    "nome": "Lickitung",
    "buster": "Mewtwo",
    "raridade": "🔹🔹",
    "chance_1_3": 0.00,
    "chance_4": 2.571,
    "chance_5": 1.714,
    "MEW": true,
    "promoA": false,
  },
  {
    "obtido": false,
    "code": "A1202",
    "nome": "Chansey",
    "buster": "Pikachu",
    "raridade": "🔹🔹",
    "chance_1_3": 0.00,
    "chance_4": 2.571,
    "chance_5": 1.714,
    "MEW": true,
    "promoA": false,
  },
  {
    "obtido": false,
    "code": "A1203",
    "nome": "Kangaskhan",
    "buster": "Charizard",
    "raridade": "🔹🔹🔹",
    "chance_1_3": 0.00,
    "chance_4": 0.357,
    "chance_5": 1.429,
    "MEW": true,
    "promoA": false,
  },
  {
    "obtido": false,
    "code": "A1204",
    "nome": "Tauros",
    "buster": "Charizard",
    "raridade": "🔹🔹",
    "chance_1_3": 0.00,
    "chance_4": 2.571,
    "chance_5": 1.714,
    "MEW": true,
    "promoA": false,
  },
  {
    "obtido": false,
    "code": "A1205",
    "nome": "Ditto",
    "buster": "Mewtwo",
    "raridade": "🔹🔹🔹",
    "chance_1_3": 0.00,
    "chance_4": 0.357,
    "chance_5": 1.429,
    "MEW": true,
    "promoA": false,
  },
  {
    "obtido": false,
    "code": "A1206",
    "nome": "Eevee",
    "buster": "Charizard",
    "raridade": "🔹",
    "chance_1_3": 2.000,
    "chance_4": 0.00,
    "chance_5": 0.00,
    "MEW": true,
    "promoA": false,
  },
  {
    "obtido": false,
    "code": "A1207",
    "nome": "Eevee",
    "buster": "Mewtwo",
    "raridade": "🔹",
    "chance_1_3": 2.000,
    "chance_4": 0.00,
    "chance_5": 0.00,
    "MEW": false,
    "promoA": false,
  },
  {
    "obtido": false,
    "code": "A1208",
    "nome": "Eevee",
    "buster": "Pikachu",
    "raridade": "🔹",
    "chance_1_3": 2.000,
    "chance_4": 0.00,
    "chance_5": 0.00,
    "MEW": false,
    "promoA": false,
  },
  {
    "obtido": false,
    "code": "A1209",
    "nome": "Porygon",
    "buster": "Mewtwo",
    "raridade": "🔹🔹",
    "chance_1_3": 0.00,
    "chance_4": 2.571,
    "chance_5": 1.714,
    "MEW": true,
    "promoA": false,
  },
  {
    "obtido": false,
    "code": "A1210",
    "nome": "Aerodactyl",
    "buster": "Mewtwo",
    "raridade": "🔹🔹🔹",
    "chance_1_3": 0.00,
    "chance_4": 0.357,
    "chance_5": 1.429,
    "MEW": true,
    "promoA": false,
  },
  {
    "obtido": false,
    "code": "A1211",
    "nome": "Snorlax",
    "buster": "Pikachu",
    "raridade": "🔹🔹🔹",
    "chance_1_3": 0.00,
    "chance_4": 0.357,
    "chance_5": 1.429,
    "MEW": true,
    "promoA": false,
  },
  {
    "obtido": false,
    "code": "A1212",
    "nome": "Minccino",
    "buster": "All",
    "raridade": "🔹",
    "chance_1_3": 2.000,
    "chance_4": 0.00,
    "chance_5": 0.00,
    "MEW": false,
    "promoA": false,
  },
  {
    "obtido": false,
    "code": "A1213",
    "nome": "Cinccino",
    "buster": "All",
    "raridade": "🔹🔹",
    "chance_1_3": 0.00,
    "chance_4": 2.571,
    "chance_5": 1.714,
    "MEW": false,
    "promoA": false,
  },
  {
    "obtido": false,
    "code": "A1214",
    "nome": "Wooloo",
    "buster": "All",
    "raridade": "🔹",
    "chance_1_3": 2.000,
    "chance_4": 0.00,
    "chance_5": 0.00,
    "MEW": false,
    "promoA": false,
  },
  {
    "obtido": false,
    "code": "A1215",
    "nome": "Dubwool",
    "buster": "All",
    "raridade": "🔹",
    "chance_1_3": 2.000,
    "chance_4": 0.00,
    "chance_5": 0.00,
    "MEW": false,
    "promoA": false,
  },
  {
    "obtido": false,
    "code": "A1216",
    "nome": "Helix Fossil",
    "buster": "Pikachu",
    "raridade": "🔹",
    "chance_1_3": 2.000,
    "chance_4": 0.00,
    "chance_5": 0.00,
    "MEW": false,
    "promoA": false,
  },
  {
    "obtido": false,
    "code": "A1217",
    "nome": "Dome Fossil",
    "buster": "Charizard",
    "raridade": "🔹",
    "chance_1_3": 2.000,
    "chance_4": 0.00,
    "chance_5": 0.00,
    "MEW": false,
    "promoA": false,
  },
  {
    "obtido": false,
    "code": "A1218",
    "nome": "Old Amber",
    "buster": "Mewtwo",
    "raridade": "🔹",
    "chance_1_3": 2.000,
    "chance_4": 0.00,
    "chance_5": 0.00,
    "MEW": false,
    "promoA": false,
  },
  {
    "obtido": false,
    "code": "A1219",
    "nome": "Erika",
    "buster": "Charizard",
    "raridade": "🔹🔹",
    "chance_1_3": 0.00,
    "chance_4": 2.571,
    "chance_5": 1.714,
    "MEW": false,
    "promoA": false,
  },
  {
    "obtido": false,
    "code": "A1220",
    "nome": "Misty",
    "buster": "Pikachu",
    "raridade": "🔹🔹",
    "chance_1_3": 0.00,
    "chance_4": 2.571,
    "chance_5": 1.714,
    "MEW": false,
    "promoA": false,
  },
  {
    "obtido": false,
    "code": "A1221",
    "nome": "Blaine",
    "buster": "Charizard",
    "raridade": "🔹🔹",
    "chance_1_3": 0.00,
    "chance_4": 2.571,
    "chance_5": 1.714,
    "MEW": false,
    "promoA": false,
  },
  {
    "obtido": false,
    "code": "A1222",
    "nome": "Koga",
    "buster": "Mewtwo",
    "raridade": "🔹🔹",
    "chance_1_3": 0.00,
    "chance_4": 2.571,
    "chance_5": 1.714,
    "MEW": false,
    "promoA": false,
  },
  {
    "obtido": false,
    "code": "A1223",
    "nome": "Giovanni",
    "buster": "Mewtwo",
    "raridade": "🔹🔹",
    "chance_1_3": 0.00,
    "chance_4": 2.571,
    "chance_5": 1.714,
    "MEW": false,
    "promoA": false,
  },
  {
    "obtido": false,
    "code": "A1224",
    "nome": "Brock",
    "buster": "Pikachu",
    "raridade": "🔹🔹",
    "chance_1_3": 0.00,
    "chance_4": 2.571,
    "chance_5": 1.714,
    "MEW": false,
    "promoA": false,
  },
  {
    "obtido": false,
    "code": "A1225",
    "nome": "Sabrina",
    "buster": "Charizard",
    "raridade": "🔹🔹",
    "chance_1_3": 0.00,
    "chance_4": 2.571,
    "chance_5": 1.714,
    "MEW": false,
    "promoA": false,
  },
  {
    "obtido": false,
    "code": "A1226",
    "nome": "Lt.Surge",
    "buster": "Pikachu",
    "raridade": "🔹🔹",
    "chance_1_3": 0.00,
    "chance_4": 2.571,
    "chance_5": 1.714,
    "MEW": false,
    "promoA": false,
  },
  {
    "obtido": false,
    "code": "A1227",
    "nome": "Bulbasaur",
    "buster": "Mewtwo",
    "raridade": "⭐️",
    "chance_1_3": 0.00,
    "chance_4": 0.322,
    "chance_5": 1.286,
    "MEW": false,
    "promoA": false,
  },
  {
    "obtido": false,
    "code": "A1228",
    "nome": "Gloom",
    "buster": "Charizard",
    "raridade": "⭐️",
    "chance_1_3": 0.00,
    "chance_4": 0.322,
    "chance_5": 1.286,
    "MEW": false,
    "promoA": false,
  },
  {
    "obtido": false,
    "code": "A1229",
    "nome": "Pinsir",
    "buster": "Charizard",
    "raridade": "⭐️",
    "chance_1_3": 0.00,
    "chance_4": 0.322,
    "chance_5": 1.286,
    "MEW": false,
    "promoA": false,
  },
  {
    "obtido": false,
    "code": "A1230",
    "nome": "Charmander",
    "buster": "Charizard",
    "raridade": "⭐️",
    "chance_1_3": 0.00,
    "chance_4": 0.322,
    "chance_5": 1.286,
    "MEW": false,
    "promoA": false,
  },
  {
    "obtido": false,
    "code": "A1231",
    "nome": "Rapidash",
    "buster": "Charizard",
    "raridade": "⭐️",
    "chance_1_3": 0.00,
    "chance_4": 0.322,
    "chance_5": 1.286,
    "MEW": false,
    "promoA": false,
  },
  {
    "obtido": false,
    "code": "A1232",
    "nome": "Squirtle",
    "buster": "Pikachu",
    "raridade": "⭐️",
    "chance_1_3": 0.00,
    "chance_4": 0.322,
    "chance_5": 1.286,
    "MEW": false,
    "promoA": false,
  },
  {
    "obtido": false,
    "code": "A1233",
    "nome": "Gyarados",
    "buster": "Pikachu",
    "raridade": "⭐️",
    "chance_1_3": 0.00,
    "chance_4": 0.322,
    "chance_5": 1.286,
    "MEW": false,
    "promoA": false,
  },
  {
    "obtido": false,
    "code": "A1234",
    "nome": "Lapras",
    "buster": "Charizard",
    "raridade": "⭐️",
    "chance_1_3": 0.00,
    "chance_4": 0.322,
    "chance_5": 1.286,
    "MEW": false,
    "promoA": false,
  },
  {
    "obtido": false,
    "code": "A1235",
    "nome": "Electrode",
    "buster": "Pikachu",
    "raridade": "⭐️",
    "chance_1_3": 0.00,
    "chance_4": 0.322,
    "chance_5": 1.286,
    "MEW": false,
    "promoA": false,
  },
  {
    "obtido": false,
    "code": "A1236",
    "nome": "Alakazam",
    "buster": "Charizard",
    "raridade": "⭐️",
    "chance_1_3": 0.00,
    "chance_4": 0.322,
    "chance_5": 1.286,
    "MEW": false,
    "promoA": false,
  },
  {
    "obtido": false,
    "code": "A1237",
    "nome": "Slowpoke",
    "buster": "Charizard",
    "raridade": "⭐️",
    "chance_1_3": 0.00,
    "chance_4": 0.322,
    "chance_5": 1.286,
    "MEW": false,
    "promoA": false,
  },
  {
    "obtido": false,
    "code": "A1238",
    "nome": "Diglett",
    "buster": "Pikachu",
    "raridade": "⭐️",
    "chance_1_3": 0.00,
    "chance_4": 0.322,
    "chance_5": 1.286,
    "MEW": false,
    "promoA": false,
  },
  {
    "obtido": false,
    "code": "A1239",
    "nome": "Cubone",
    "buster": "Mewtwo",
    "raridade": "⭐️",
    "chance_1_3": 0.00,
    "chance_4": 0.322,
    "chance_5": 1.286,
    "MEW": false,
    "promoA": false,
  },
  {
    "obtido": false,
    "code": "A1240",
    "nome": "Nidoqueen",
    "buster": "Pikachu",
    "raridade": "⭐️",
    "chance_1_3": 0.00,
    "chance_4": 0.322,
    "chance_5": 1.286,
    "MEW": false,
    "promoA": false,
  },
  {
    "obtido": false,
    "code": "A1241",
    "nome": "Nidoking",
    "buster": "Pikachu",
    "raridade": "⭐️",
    "chance_1_3": 0.00,
    "chance_4": 0.322,
    "chance_5": 1.286,
    "MEW": false,
    "promoA": false,
  },
  {
    "obtido": false,
    "code": "A1242",
    "nome": "Golbat",
    "buster": "Mewtwo",
    "raridade": "⭐️",
    "chance_1_3": 0.00,
    "chance_4": 0.322,
    "chance_5": 1.286,
    "MEW": false,
    "promoA": false,
  },
  {
    "obtido": false,
    "code": "A1243",
    "nome": "Weezing",
    "buster": "Mewtwo",
    "raridade": "⭐️",
    "chance_1_3": 0.00,
    "chance_4": 0.322,
    "chance_5": 1.286,
    "MEW": false,
    "promoA": false,
  },
  {
    "obtido": false,
    "code": "A1244",
    "nome": "Dragonite",
    "buster": "Mewtwo",
    "raridade": "⭐️",
    "chance_1_3": 0.00,
    "chance_4": 0.322,
    "chance_5": 1.286,
    "MEW": false,
    "promoA": false,
  },
  {
    "obtido": false,
    "code": "A1245",
    "nome": "Pidgeot",
    "buster": "Mewtwo",
    "raridade": "⭐️",
    "chance_1_3": 0.00,
    "chance_4": 0.322,
    "chance_5": 1.286,
    "MEW": false,
    "promoA": false,
  },
  {
    "obtido": false,
    "code": "A1246",
    "nome": "Meowth",
    "buster": "Charizard",
    "raridade": "⭐️",
    "chance_1_3": 0.00,
    "chance_4": 0.322,
    "chance_5": 1.286,
    "MEW": false,
    "promoA": false,
  },
  {
    "obtido": false,
    "code": "A1247",
    "nome": "Ditto",
    "buster": "Mewtwo",
    "raridade": "⭐️",
    "chance_1_3": 0.00,
    "chance_4": 0.322,
    "chance_5": 1.286,
    "MEW": false,
    "promoA": false,
  },
  {
    "obtido": false,
    "code": "A1248",
    "nome": "Eevee",
    "buster": "Pikachu",
    "raridade": "⭐️",
    "chance_1_3": 0.00,
    "chance_4": 0.322,
    "chance_5": 1.286,
    "MEW": false,
    "promoA": false,
  },
  {
    "obtido": false,
    "code": "A1249",
    "nome": "Porygon",
    "buster": "Mewtwo",
    "raridade": "⭐️",
    "chance_1_3": 0.00,
    "chance_4": 0.322,
    "chance_5": 1.286,
    "MEW": false,
    "promoA": false,
  },
  {
    "obtido": false,
    "code": "A1250",
    "nome": "Snorlax",
    "buster": "Pikachu",
    "raridade": "⭐️",
    "chance_1_3": 0.00,
    "chance_4": 0.322,
    "chance_5": 1.286,
    "MEW": false,
    "promoA": false,
  },
  {
    "obtido": false,
    "code": "A1251",
    "nome": "Venusaur ex",
    "buster": "Mewtwo",
    "raridade": "⭐️⭐️",
    "chance_1_3": 0.00,
    "chance_4": 0.056,
    "chance_5": 0.222,
    "MEW": false,
    "promoA": false,
  },
  {
    "obtido": false,
    "code": "A1252",
    "nome": "Exeggutor ex",
    "buster": "Charizard",
    "raridade": "⭐️⭐️",
    "chance_1_3": 0.00,
    "chance_4": 0.050,
    "chance_5": 0.200,
    "MEW": false,
    "promoA": false,
  },
  {
    "obtido": false,
    "code": "A1253",
    "nome": "Charizard ex",
    "buster": "Charizard",
    "raridade": "⭐️⭐️",
    "chance_1_3": 0.00,
    "chance_4": 0.050,
    "chance_5": 0.200,
    "MEW": false,
    "promoA": false,
  },
  {
    "obtido": false,
    "code": "A1254",
    "nome": "Arcanine ex",
    "buster": "Pikachu",
    "raridade": "⭐️⭐️",
    "chance_1_3": 0.00,
    "chance_4": 0.050,
    "chance_5": 0.200,
    "MEW": false,
    "promoA": false,
  },
  {
    "obtido": false,
    "code": "A1255",
    "nome": "Moltres ex",
    "buster": "Charizard",
    "raridade": "⭐️⭐️",
    "chance_1_3": 0.00,
    "chance_4": 0.050,
    "chance_5": 0.200,
    "MEW": false,
    "promoA": false,
  },
  {
    "obtido": false,
    "code": "A1256",
    "nome": "Blastoise ex",
    "buster": "Pikachu",
    "raridade": "⭐️⭐️",
    "chance_1_3": 0.00,
    "chance_4": 0.050,
    "chance_5": 0.200,
    "MEW": false,
    "promoA": false,
  },
  {
    "obtido": false,
    "code": "A1257",
    "nome": "Starmie ex",
    "buster": "Charizard",
    "raridade": "⭐️⭐️",
    "chance_1_3": 0.00,
    "chance_4": 0.050,
    "chance_5": 0.200,
    "MEW": false,
    "promoA": false,
  },
  {
    "obtido": false,
    "code": "A1258",
    "nome": "Articuno ex",
    "buster": "Mewtwo",
    "raridade": "⭐️⭐️",
    "chance_1_3": 0.00,
    "chance_4": 0.056,
    "chance_5": 0.222,
    "MEW": false,
    "promoA": false,
  },
  {
    "obtido": false,
    "code": "A1259",
    "nome": "Pikachu ex",
    "buster": "Pikachu",
    "raridade": "⭐️⭐️",
    "chance_1_3": 0.00,
    "chance_4": 0.050,
    "chance_5": 0.200,
    "MEW": false,
    "promoA": false,
  },
  {
    "obtido": false,
    "code": "A1260",
    "nome": "Zapdos ex",
    "buster": "Pikachu",
    "raridade": "⭐️⭐️",
    "chance_1_3": 0.00,
    "chance_4": 0.050,
    "chance_5": 0.200,
    "MEW": false,
    "promoA": false,
  },
  {
    "obtido": false,
    "code": "A1261",
    "nome": "Gengar ex",
    "buster": "Mewtwo",
    "raridade": "⭐️⭐️",
    "chance_1_3": 0.00,
    "chance_4": 0.056,
    "chance_5": 0.222,
    "MEW": false,
    "promoA": false,
  },
  {
    "obtido": false,
    "code": "A1262",
    "nome": "Mewtwo ex",
    "buster": "Mewtwo",
    "raridade": "⭐️⭐️",
    "chance_1_3": 0.00,
    "chance_4": 0.056,
    "chance_5": 0.222,
    "MEW": false,
    "promoA": false,
  },
  {
    "obtido": false,
    "code": "A1263",
    "nome": "Machamp ex",
    "buster": "Charizard",
    "raridade": "⭐️⭐️",
    "chance_1_3": 0.00,
    "chance_4": 0.050,
    "chance_5": 0.200,
    "MEW": false,
    "promoA": false,
  },
  {
    "obtido": false,
    "code": "A1264",
    "nome": "Marowak ex",
    "buster": "Mewtwo",
    "raridade": "⭐️⭐️",
    "chance_1_3": 0.00,
    "chance_4": 0.056,
    "chance_5": 0.222,
    "MEW": false,
    "promoA": false,
  },
  {
    "obtido": false,
    "code": "A1265",
    "nome": "Wigglytuff ex",
    "buster": "Pikachu",
    "raridade": "⭐️⭐️",
    "chance_1_3": 0.00,
    "chance_4": 0.050,
    "chance_5": 0.200,
    "MEW": false,
    "promoA": false,
  },
  {
    "obtido": false,
    "code": "A1266",
    "nome": "Erika",
    "buster": "Charizard",
    "raridade": "⭐️⭐️",
    "chance_1_3": 0.00,
    "chance_4": 0.050,
    "chance_5": 0.200,
    "MEW": false,
    "promoA": false,
  },
  {
    "obtido": false,
    "code": "A1267",
    "nome": "Misty",
    "buster": "Pikachu",
    "raridade": "⭐️⭐️",
    "chance_1_3": 0.00,
    "chance_4": 0.050,
    "chance_5": 0.200,
    "MEW": false,
    "promoA": false,
  },
  {
    "obtido": false,
    "code": "A1268",
    "nome": "Blaine",
    "buster": "Charizard",
    "raridade": "⭐️⭐️",
    "chance_1_3": 0.00,
    "chance_4": 0.050,
    "chance_5": 0.200,
    "MEW": false,
    "promoA": false,
  },
  {
    "obtido": false,
    "code": "A1269",
    "nome": "Koga",
    "buster": "Mewtwo",
    "raridade": "⭐️⭐️",
    "chance_1_3": 0.00,
    "chance_4": 0.056,
    "chance_5": 0.222,
    "MEW": false,
    "promoA": false,
  },
  {
    "obtido": false,
    "code": "A1270",
    "nome": "Giovanni",
    "buster": "Mewtwo",
    "raridade": "⭐️⭐️",
    "chance_1_3": 0.00,
    "chance_4": 0.056,
    "chance_5": 0.222,
    "MEW": false,
    "promoA": false,
  },
  {
    "obtido": false,
    "code": "A1271",
    "nome": "Brock",
    "buster": "Pikachu",
    "raridade": "⭐️⭐️",
    "chance_1_3": 0.00,
    "chance_4": 0.050,
    "chance_5": 0.200,
    "MEW": false,
    "promoA": false,
  },
  {
    "obtido": false,
    "code": "A1272",
    "nome": "Sabrina",
    "buster": "Charizard",
    "raridade": "⭐️⭐️",
    "chance_1_3": 0.00,
    "chance_4": 0.050,
    "chance_5": 0.200,
    "MEW": false,
    "promoA": false,
  },
  {
    "obtido": false,
    "code": "A1273",
    "nome": "Lt.Surge",
    "buster": "Pikachu",
    "raridade": "⭐️⭐️",
    "chance_1_3": 0.00,
    "chance_4": 0.050,
    "chance_5": 0.200,
    "MEW": false,
    "promoA": false,
  },
  {
    "obtido": false,
    "code": "A1274",
    "nome": "Moltres ex",
    "buster": "Charizard",
    "raridade": "⭐️⭐️",
    "chance_1_3": 0.00,
    "chance_4": 0.050,
    "chance_5": 0.200,
    "MEW": false,
    "promoA": false,
  },
  {
    "obtido": false,
    "code": "A1275",
    "nome": "Articuno ex",
    "buster": "Mewtwo",
    "raridade": "⭐️⭐️",
    "chance_1_3": 0.00,
    "chance_4": 0.056,
    "chance_5": 0.222,
    "MEW": false,
    "promoA": false,
  },
  {
    "obtido": false,
    "code": "A1276",
    "nome": "Zapdos ex",
    "buster": "Pikachu",
    "raridade": "⭐️⭐️",
    "chance_1_3": 0.00,
    "chance_4": 0.050,
    "chance_5": 0.200,
    "MEW": false,
    "promoA": false,
  },
  {
    "obtido": false,
    "code": "A1277",
    "nome": "Gengar ex",
    "buster": "Mewtwo",
    "raridade": "⭐️⭐️",
    "chance_1_3": 0.00,
    "chance_4": 0.056,
    "chance_5": 0.222,
    "MEW": false,
    "promoA": false,
  },
  {
    "obtido": false,
    "code": "A1278",
    "nome": "Machamp ex",
    "buster": "Charizard",
    "raridade": "⭐️⭐️",
    "chance_1_3": 0.00,
    "chance_4": 0.050,
    "chance_5": 0.200,
    "MEW": false,
    "promoA": false,
  },
  {
    "obtido": false,
    "code": "A1279",
    "nome": "Wigglytuff ex",
    "buster": "Pikachu",
    "raridade": "⭐️⭐️",
    "chance_1_3": 0.00,
    "chance_4": 0.050,
    "chance_5": 0.200,
    "MEW": false,
    "promoA": false,
  },
  {
    "obtido": false,
    "code": "A1280",
    "nome": "Charizard ex",
    "buster": "Charizard",
    "raridade": "⭐️⭐️⭐️",
    "chance_1_3": 0.00,
    "chance_4": 0.222,
    "chance_5": 0.888,
    "MEW": false,
    "promoA": false,
  },
  {
    "obtido": false,
    "code": "A1281",
    "nome": "Pikachu ex",
    "buster": "Pikachu",
    "raridade": "⭐️⭐️⭐️",
    "chance_1_3": 0.00,
    "chance_4": 0.222,
    "chance_5": 0.888,
    "MEW": false,
    "promoA": false,
  },
  {
    "obtido": false,
    "code": "A1282",
    "nome": "Mewtwo ex",
    "buster": "Mewtwo",
    "raridade": "⭐️⭐️⭐️",
    "chance_1_3": 0.00,
    "chance_4": 0.222,
    "chance_5": 0.888,
    "MEW": false,
    "promoA": false,
  },
  {
    "obtido": false,
    "code": "A1283",
    "nome": "Mew",
    "buster": "Mission",
    "raridade": "👑",
    "chance_1_3": 0.00,
    "chance_4": 0.00,
    "chance_5": 0.00,
    "MEW": false,
    "promoA": false,
  },
  {
    "obtido": false,
    "code": "A1284",
    "nome": "Charizard ex",
    "buster": "All",
    "raridade": "👑",
    "chance_1_3": 0.00,
    "chance_4": 0.013,
    "chance_5": 0.053,
    "MEW": false,
    "promoA": false,
  },
  {
    "obtido": false,
    "code": "A1285",
    "nome": "Pikachu ex",
    "buster": "All",
    "raridade": "👑",
    "chance_1_3": 0.00,
    "chance_4": 0.013,
    "chance_5": 0.053,
    "MEW": false,
    "promoA": false,
  },
  {
    "obtido": false,
    "code": "A1286",
    "nome": "Mewtwo ex",
    "buster": "All",
    "raridade": "👑",
    "chance_1_3": 0.00,
    "chance_4": 0.013,
    "chance_5": 0.053,
    "MEW": false,
    "promoA": false,
  },
  {
    "obtido": false,
    "code": "P-A001",
    "nome": "Potion",
    "buster": "Shop",
    "raridade": "promoA",
    "chance_1_3": 0.00,
    "chance_4": 0.000,
    "chance_5": 0.000,
    "MEW": false,
    "promoA": true,
  },
  {
    "obtido": false,
    "code": "P-A002",
    "nome": "X speed",
    "buster": "Shop",
    "raridade": "promoA",
    "chance_1_3": 0.00,
    "chance_4": 0.000,
    "chance_5": 0.000,
    "MEW": false,
    "promoA": true,
  },
  {
    "obtido": false,
    "code": "P-A003",
    "nome": "Hand scope",
    "buster": "Shop",
    "raridade": "promoA",
    "chance_1_3": 0.00,
    "chance_4": 0.000,
    "chance_5": 0.000,
    "MEW": false,
    "promoA": true,
  },
  {
    "obtido": false,
    "code": "P-A004",
    "nome": "Pokedex",
    "buster": "Shop",
    "raridade": "promoA",
    "chance_1_3": 0.00,
    "chance_4": 0.000,
    "chance_5": 0.000,
    "MEW": false,
    "promoA": true,
  },
  {
    "obtido": false,
    "code": "P-A005",
    "nome": "Poke ball",
    "buster": "Shop",
    "raridade": "promoA",
    "chance_1_3": 0.00,
    "chance_4": 0.000,
    "chance_5": 0.000,
    "MEW": false,
    "promoA": true,
  },
  {
    "obtido": false,
    "code": "P-A006",
    "nome": "Redcard",
    "buster": "Shop",
    "raridade": "promoA",
    "chance_1_3": 0.00,
    "chance_4": 0.000,
    "chance_5": 0.000,
    "MEW": false,
    "promoA": true,
  },
  {
    "obtido": false,
    "code": "P-A007",
    "nome": "Professor 's Research",
    "buster": "Shop",
    "raridade": "promoA",
    "chance_1_3": 0.00,
    "chance_4": 0.000,
    "chance_5": 0.000,
    "MEW": false,
    "promoA": true,
  },
  {
    "obtido": false,
    "code": "P-A008",
    "nome": "???",
    "buster": "???",
  },
  {
    "obtido": false,
    "code": "P-A009",
    "nome": "Pikachu",
    "buster": "Shop",
    "raridade": "promoA",
    "chance_1_3": 0.00,
    "chance_4": 0.000,
    "chance_5": 0.000,
    "MEW": false,
    "promoA": true,
  },
  {
    "obtido": false,
    "code": "P-A010",
    "nome": "Mewtwo",
    "buster": "Mission",
    "raridade": "promoA",
    "chance_1_3": 0.00,
    "chance_4": 0.000,
    "chance_5": 0.000,
    "MEW": false,
    "promoA": true,
  },
  {
    "obtido": false,
    "code": "P-A011",
    "nome": "Chansey",
    "buster": "Wonder Pick",
    "raridade": "promoA",
    "chance_1_3": 0.00,
    "chance_4": 0.000,
    "chance_5": 0.000,
    "MEW": false,
    "promoA": true,
  },
  {
    "obtido": false,
    "code": "P-A012",
    "nome": "Meowth",
    "buster": "Wonder Pick",
    "raridade": "promoA",
    "chance_1_3": 0.00,
    "chance_4": 0.000,
    "chance_5": 0.000,
    "MEW": false,
    "promoA": true,
  },
  {
    "obtido": false,
    "code": "P-A013",
    "nome": "Butterfree",
    "buster": "Promo pack",
    "raridade": "promoA",
    "chance_1_3": 0.00,
    "chance_4": 0.000,
    "chance_5": 0.000,
    "MEW": false,
    "promoA": true,
  },
  {
    "obtido": false,
    "code": "P-A014",
    "nome": "Lapras ex",
    "buster": "Promo pack",
    "raridade": "promoA",
    "chance_1_3": 0.00,
    "chance_4": 0.000,
    "chance_5": 0.000,
    "MEW": false,
    "promoA": true,
  },
  {
    "obtido": false,
    "code": "P-A015",
    "nome": "Pikachu",
    "buster": "Promo pack",
    "raridade": "promoA",
    "chance_1_3": 0.00,
    "chance_4": 0.000,
    "chance_5": 0.000,
    "MEW": false,
    "promoA": true,
  },
  {
    "obtido": false,
    "code": "P-A016",
    "nome": "Clefairy",
    "buster": "Promo pack",
    "raridade": "promoA",
    "chance_1_3": 0.00,
    "chance_4": 0.000,
    "chance_5": 0.000,
    "MEW": false,
    "promoA": true,
  },
  {
    "obtido": false,
    "code": "P-A017",
    "nome": "Mankey",
    "buster": "Promo pack",
    "raridade": "promoA",
    "chance_1_3": 0.00,
    "chance_4": 0.000,
    "chance_5": 0.000,
    "MEW": false,
    "promoA": true,
  },
  {
    "obtido": false,
    "code": "P-A018",
    "nome": "Venusaur",
    "buster": "Promo pack",
    "raridade": "promoA",
    "chance_1_3": 0.00,
    "chance_4": 0.000,
    "chance_5": 0.000,
    "MEW": false,
    "promoA": true,
  },
  {
    "obtido": false,
    "code": "P-A019",
    "nome": "Greninja",
    "buster": "Promo pack",
    "raridade": "promoA",
    "chance_1_3": 0.00,
    "chance_4": 0.000,
    "chance_5": 0.000,
    "MEW": false,
    "promoA": true,
  },
  {
    "obtido": false,
    "code": "P-A020",
    "nome": "Haunter",
    "buster": "Promo pack",
    "raridade": "promoA",
    "chance_1_3": 0.00,
    "chance_4": 0.000,
    "chance_5": 0.000,
    "MEW": false,
    "promoA": true,
  },
  {
    "obtido": false,
    "code": "P-A021",
    "nome": "Onix",
    "buster": "Promo pack",
    "raridade": "promoA",
    "chance_1_3": 0.00,
    "chance_4": 0.000,
    "chance_5": 0.000,
    "MEW": false,
    "promoA": true,
  },
  {
    "obtido": false,
    "code": "P-A022",
    "nome": "Jigglypuff",
    "buster": "Promo pack",
    "raridade": "promoA",
    "chance_1_3": 0.00,
    "chance_4": 0.000,
    "chance_5": 0.000,
    "MEW": false,
    "promoA": true,
  },
  {
    "obtido": false,
    "code": "P-A023",
    "nome": "Bulbasaur",
    "buster": "Wonder Pick",
    "raridade": "promoA",
    "chance_1_3": 0.00,
    "chance_4": 0.000,
    "chance_5": 0.000,
    "MEW": false,
    "promoA": true,
  },
  {
    "obtido": false,
    "code": "P-A024",
    "nome": "Magnemite",
    "buster": "Wonder Pick",
    "raridade": "promoA",
    "chance_1_3": 0.00,
    "chance_4": 0.000,
    "chance_5": 0.000,
    "MEW": false,
    "promoA": true,
  },
  {
    "obtido": false,
    "code": "P-A025",
    "nome": "Venosaur",
    "buster": "Promo pack",
    "raridade": "promoA",
    "chance_1_3": 0.00,
    "chance_4": 0.000,
    "chance_5": 0.000,
    "MEW": false,
    "promoA": true,
  },
  {
    "obtido": false,
    "code": "P-A026",
    "nome": "Greninja",
    "buster": "Promo pack",
    "raridade": "promoA",
    "chance_1_3": 0.00,
    "chance_4": 0.000,
    "chance_5": 0.000,
    "MEW": false,
    "promoA": true,
  },
  {
    "obtido": false,
    "code": "P-A027",
    "nome": "Haunter",
    "buster": "Promo pack",
    "raridade": "promoA",
    "chance_1_3": 0.00,
    "chance_4": 0.000,
    "chance_5": 0.000,
    "MEW": false,
    "promoA": true,
  },
  {
    "obtido": false,
    "code": "P-A028",
    "nome": "Onix",
    "buster": "Promo pack",
    "raridade": "promoA",
    "chance_1_3": 0.00,
    "chance_4": 0.000,
    "chance_5": 0.000,
    "MEW": false,
    "promoA": true,
  },
  {
    "obtido": false,
    "code": "P-A029",
    "nome": "Jigglypuff",
    "buster": "Promo pack",
    "raridade": "promoA",
    "chance_1_3": 0.00,
    "chance_4": 0.000,
    "chance_5": 0.000,
    "MEW": false,
    "promoA": true,
  },
  // Nova Coleção MEW
  {
    "obtido": false,
    "code": "A1A001",
    "nome": "Exeggcute",
    "buster": "MEW",
    "raridade": "🔹",
    "chance_1_3": 3.135,
    "chance_4": 0.00,
    "chance_5": 0.00,
    "MEW": false,
    "promoA": false,
  },
  {
    "obtido": false,
    "code": "A1A002",
    "nome": "Exeggutor",
    "buster": "MEW",
    "raridade": "🔹🔹",
    "chance_1_3": 0.00,
    "chance_4": 3.913,
    "chance_5": 2.609,
    "MEW": false,
    "promoA": false,
  },
  {
    "obtido": false,
    "code": "A1A003",
    "nome": "Celebi ex",
    "buster": "MEW",
    "raridade": "🔹🔹🔹🔹",
    "chance_1_3": 0.00,
    "chance_4": 0.333,
    "chance_5": 1.333,
    "MEW": false,
    "promoA": false,
  },
  {
    "obtido": false,
    "code": "A1A004",
    "nome": "Snivy",
    "buster": "MEW",
    "raridade": "🔹",
    "chance_1_3": 3.125,
    "chance_4": 0.000,
    "chance_5": 0.000,
    "MEW": false,
    "promoA": false,
  },
  {
    "obtido": false,
    "code": "A1A005",
    "nome": "Servine",
    "buster": "MEW",
    "raridade": "🔹🔹",
    "chance_1_3": 0.000,
    "chance_4": 3.913,
    "chance_5": 2.609,
    "MEW": false,
    "promoA": false,
  },
  {
    "obtido": false,
    "code": "A1A006",
    "nome": "Serperior",
    "buster": "MEW",
    "raridade": "🔹🔹🔹",
    "chance_1_3": 0.000,
    "chance_4": 0.625,
    "chance_5": 2.500,
    "MEW": false,
    "promoA": false, //Até aqui
  },
  {
    "obtido": false,
    "code": "A1A007",
    "nome": "Butterfree",
    "buster": "MEW",
    "raridade": "🔹🔹🔹",
    "chance_1_3": 0.00,
    "chance_4": 0.357,
    "chance_5": 1.429,
    "MEW": false,
    "promoA": false,
  },
  {
    "obtido": false,
    "code": "A1A008",
    "nome": "Weedle",
    "buster": "MEW",
    "raridade": "🔹",
    "chance_1_3": 2.000,
    "chance_4": 0.00,
    "chance_5": 0.00,
    "MEW": false,
    "promoA": false,
  },
  {
    "obtido": false,
    "code": "A1A009",
    "nome": "Kakuna",
    "buster": "MEW",
    "raridade": "🔹",
    "chance_1_3": 2.000,
    "chance_4": 0.00,
    "chance_5": 0.00,
    "MEW": false,
    "promoA": false,
  },
  {
    "obtido": false,
    "code": "A1A010",
    "nome": "Beedrill",
    "buster": "MEW",
    "raridade": "🔹🔹🔹",
    "chance_1_3": 0.00,
    "chance_4": 0.357,
    "chance_5": 1.429,
    "MEW": false,
    "promoA": false,
  },
  {
    "obtido": false,
    "code": "A1A011",
    "nome": "Oddish",
    "buster": "MEW",
    "raridade": "🔹",
    "chance_1_3": 2.000,
    "chance_4": 0.00,
    "chance_5": 0.00,
    "MEW": false,
    "promoA": false,
  },
  {
    "obtido": false,
    "code": "A1A012",
    "nome": "Gloom",
    "buster": "MEW",
    "raridade": "🔹🔹",
    "chance_1_3": 0.00,
    "chance_4": 2.571,
    "chance_5": 1.714,
    "MEW": false,
    "promoA": false,
  },
  {
    "obtido": false,
    "code": "A1A013",
    "nome": "Vileplume",
    "buster": "MEW",
    "raridade": "🔹🔹🔹",
    "chance_1_3": 0.00,
    "chance_4": 0.357,
    "chance_5": 1.429,
    "MEW": false,
    "promoA": false,
  },
  {
    "obtido": false,
    "code": "A1A014",
    "nome": "Paras",
    "buster": "MEW",
    "raridade": "🔹",
    "chance_1_3": 2.000,
    "chance_4": 0.00,
    "chance_5": 0.00,
    "MEW": false,
    "promoA": false,
  },
  {
    "obtido": false,
    "code": "A1A015",
    "nome": "Parasect",
    "buster": "MEW",
    "raridade": "🔹🔹",
    "chance_1_3": 0.00,
    "chance_4": 2.571,
    "chance_5": 1.714,
    "MEW": false,
    "promoA": false,
  },
  {
    "obtido": false,
    "code": "A1A016",
    "nome": "Venonat",
    "buster": "MEW",
    "raridade": "🔹",
    "chance_1_3": 2.000,
    "chance_4": 0.00,
    "chance_5": 0.00,
    "MEW": false,
    "promoA": false,
  },
  {
    "obtido": false,
    "code": "A1A017",
    "nome": "Venomoth",
    "buster": "MEW",
    "raridade": "🔹🔹",
    "chance_1_3": 0.00,
    "chance_4": 2.571,
    "chance_5": 1.714,
    "MEW": false,
    "promoA": false,
  },
  {
    "obtido": false,
    "code": "A1A018",
    "nome": "Bellsprout",
    "buster": "MEW",
    "raridade": "🔹",
    "chance_1_3": 2.000,
    "chance_4": 0.00,
    "chance_5": 0.00,
    "MEW": false,
    "promoA": false,
  },
  {
    "obtido": false,
    "code": "A1A019",
    "nome": "Weepinbell",
    "buster": "MEW",
    "raridade": "🔹🔹",
    "chance_1_3": 0.00,
    "chance_4": 2.571,
    "chance_5": 1.714,
    "MEW": false,
    "promoA": false,
  },
  {
    "obtido": false,
    "code": "A1A020",
    "nome": "Victreebel",
    "buster": "MEW",
    "raridade": "🔹🔹🔹",
    "chance_1_3": 0.00,
    "chance_4": 0.357,
    "chance_5": 1.429,
    "MEW": false,
    "promoA": false,
  },
  {
    "obtido": false,
    "code": "A1A021",
    "nome": "Exeggcute",
    "buster": "MEW",
    "raridade": "🔹",
    "chance_1_3": 2.000,
    "chance_4": 0.00,
    "chance_5": 0.00,
    "MEW": false,
    "promoA": false,
  },
  {
    "obtido": false,
    "code": "A1A022",
    "nome": "Exeggutor",
    "buster": "MEW",
    "raridade": "🔹🔹🔹",
    "chance_1_3": 0.00,
    "chance_4": 0.357,
    "chance_5": 1.429,
    "MEW": false,
    "promoA": false,
  },
  {
    "obtido": false,
    "code": "A1A023",
    "nome": "Exeggutor ex",
    "buster": "MEW",
    "raridade": "🔹🔹🔹🔹",
    "chance_1_3": 0.00,
    "chance_4": 0.333,
    "chance_5": 1.333,
    "MEW": false,
    "promoA": false,
  },
  {
    "obtido": false,
    "code": "A1A024",
    "nome": "Tangela",
    "buster": "MEW",
    "raridade": "🔹",
    "chance_1_3": 2.000,
    "chance_4": 0.00,
    "chance_5": 0.00,
    "MEW": false,
    "promoA": false,
  },
  {
    "obtido": false,
    "code": "A1A025",
    "nome": "Scyther",
    "buster": "MEW",
    "raridade": "🔹",
    "chance_1_3": 2.000,
    "chance_4": 0.00,
    "chance_5": 0.00,
    "MEW": false,
    "promoA": false,
  },
  {
    "obtido": false,
    "code": "A1A026",
    "nome": "Pinsir",
    "buster": "MEW",
    "raridade": "🔹🔹",
    "chance_1_3": 0.00,
    "chance_4": 2.571,
    "chance_5": 1.714,
    "MEW": false,
    "promoA": false,
  },
  {
    "obtido": false,
    "code": "A1A027",
    "nome": "Cottonee",
    "buster": "MEW",
    "raridade": "🔹",
    "chance_1_3": 2.000,
    "chance_4": 0.00,
    "chance_5": 0.00,
    "MEW": false,
    "promoA": false,
  },
  {
    "obtido": false,
    "code": "A1A028",
    "nome": "Whimsicott",
    "buster": "MEW",
    "raridade": "🔹🔹",
    "chance_1_3": 0.00,
    "chance_4": 2.571,
    "chance_5": 1.714,
    "MEW": false,
    "promoA": false,
  },
  {
    "obtido": false,
    "code": "A1A029",
    "nome": "Petilil",
    "buster": "MEW",
    "raridade": "🔹",
    "chance_1_3": 2.000,
    "chance_4": 0.00,
    "chance_5": 0.00,
    "MEW": false,
    "promoA": false,
  },
  {
    "obtido": false,
    "code": "A1A030",
    "nome": "Lilligant",
    "buster": "MEW",
    "raridade": "🔹🔹",
    "chance_1_3": 0.00,
    "chance_4": 2.571,
    "chance_5": 1.714,
    "MEW": false,
    "promoA": false,
  },
  {
    "obtido": false,
    "code": "A1A031",
    "nome": "Skiddo",
    "buster": "MEW",
    "raridade": "🔹",
    "chance_1_3": 2.000,
    "chance_4": 0.00,
    "chance_5": 0.00,
    "MEW": false,
    "promoA": false,
  },
  {
    "obtido": false,
    "code": "A1A032",
    "nome": "Gogoat",
    "buster": "MEW",
    "raridade": "🔹",
    "chance_1_3": 2.000,
    "chance_4": 0.00,
    "chance_5": 0.00,
    "MEW": false,
    "promoA": false,
  },
  {
    "obtido": false,
    "code": "A1A033",
    "nome": "Charmander",
    "buster": "MEW",
    "raridade": "🔹",
    "chance_1_3": 2.000,
    "chance_4": 0.00,
    "chance_5": 0.00,
    "MEW": false,
    "promoA": false,
  },
  {
    "obtido": false,
    "code": "A1A034",
    "nome": "Charmeleon",
    "buster": "MEW",
    "raridade": "🔹🔹",
    "chance_1_3": 0.00,
    "chance_4": 2.571,
    "chance_5": 1.714,
    "MEW": false,
    "promoA": false,
  },
  {
    "obtido": false,
    "code": "A1A035",
    "nome": "Charizard",
    "buster": "MEW",
    "raridade": "🔹🔹🔹",
    "chance_1_3": 0.00,
    "chance_4": 0.357,
    "chance_5": 1.429,
    "MEW": false,
    "promoA": false,
  },
  {
    "obtido": false,
    "code": "A1A036",
    "nome": "Charizard ex",
    "buster": "MEW",
    "raridade": "🔹🔹🔹🔹",
    "chance_1_3": 0.00,
    "chance_4": 0.333,
    "chance_5": 1.333,
    "MEW": false,
    "promoA": false,
  },
  {
    "obtido": false,
    "code": "A1A037",
    "nome": "Vulpix",
    "buster": "MEW",
    "raridade": "🔹",
    "chance_1_3": 2.000,
    "chance_4": 0.00,
    "chance_5": 0.00,
    "MEW": false,
    "promoA": false,
  },
  {
    "obtido": false,
    "code": "A1A038",
    "nome": "Ninetales",
    "buster": "MEW",
    "raridade": "🔹🔹",
    "chance_1_3": 0.00,
    "chance_4": 2.571,
    "chance_5": 1.714,
    "MEW": false,
    "promoA": false,
  },
  {
    "obtido": false,
    "code": "A1A039",
    "nome": "Growlithe",
    "buster": "MEW",
    "raridade": "🔹",
    "chance_1_3": 2.000,
    "chance_4": 0.00,
    "chance_5": 0.00,
    "MEW": false,
    "promoA": false,
  },
  {
    "obtido": false,
    "code": "A1A040",
    "nome": "Arcanine",
    "buster": "MEW",
    "raridade": "🔹🔹🔹",
    "chance_1_3": 0.00,
    "chance_4": 0.357,
    "chance_5": 1.429,
    "MEW": false,
    "promoA": false,
  },
  {
    "obtido": false,
    "code": "A1A041",
    "nome": "Arcanine ex",
    "buster": "MEW",
    "raridade": "🔹🔹🔹🔹",
    "chance_1_3": 0.00,
    "chance_4": 0.333,
    "chance_5": 1.333,
    "MEW": false,
    "promoA": false,
  },
  {
    "obtido": false,
    "code": "A1A042",
    "nome": "Ponyta",
    "buster": "MEW",
    "raridade": "🔹",
    "chance_1_3": 2.000,
    "chance_4": 0.00,
    "chance_5": 0.00,
    "MEW": false,
    "promoA": false,
  },
  {
    "obtido": false,
    "code": "A1A043",
    "nome": "Rapidash",
    "buster": "MEW",
    "raridade": "🔹🔹",
    "chance_1_3": 0.00,
    "chance_4": 2.571,
    "chance_5": 1.714,
    "MEW": false,
    "promoA": false,
  },
  {
    "obtido": false,
    "code": "A1A044",
    "nome": "Magmar",
    "buster": "MEW",
    "raridade": "🔹",
    "chance_1_3": 2.000,
    "chance_4": 0.00,
    "chance_5": 0.00,
    "MEW": false,
    "promoA": false,
  },
  {
    "obtido": false,
    "code": "A1A045",
    "nome": "Flareon",
    "buster": "MEW",
    "raridade": "🔹🔹🔹",
    "chance_1_3": 0.00,
    "chance_4": 0.357,
    "chance_5": 1.429,
    "MEW": false,
    "promoA": false,
  },
  {
    "obtido": false,
    "code": "A1A046",
    "nome": "Moltres",
    "buster": "MEW",
    "raridade": "🔹🔹🔹",
    "chance_1_3": 0.00,
    "chance_4": 0.357,
    "chance_5": 1.429,
    "MEW": false,
    "promoA": false,
  },
  {
    "obtido": false,
    "code": "A1A047",
    "nome": "Moltres ex",
    "buster": "MEW",
    "raridade": "🔹🔹🔹🔹",
    "chance_1_3": 0.00,
    "chance_4": 0.333,
    "chance_5": 1.333,
    "MEW": false,
    "promoA": false,
  },
  {
    "obtido": false,
    "code": "A1A048",
    "nome": "Heatmor",
    "buster": "MEW",
    "raridade": "🔹",
    "chance_1_3": 2.000,
    "chance_4": 0.00,
    "chance_5": 0.00,
    "MEW": false,
    "promoA": false,
  },
  {
    "obtido": false,
    "code": "A1A049",
    "nome": "Salandit",
    "buster": "MEW",
    "raridade": "🔹",
    "chance_1_3": 2.000,
    "chance_4": 0.00,
    "chance_5": 0.00,
    "MEW": false,
    "promoA": false,
  },
  {
    "obtido": false,
    "code": "A1A050",
    "nome": "Salazzle",
    "buster": "MEW",
    "raridade": "🔹",
    "chance_1_3": 2.000,
    "chance_4": 0.00,
    "chance_5": 0.00,
    "MEW": false,
    "promoA": false,
  },
  {
    "obtido": false,
    "code": "A1A051",
    "nome": "Sizzlipede",
    "buster": "MEW",
    "raridade": "🔹",
    "chance_1_3": 2.000,
    "chance_4": 0.00,
    "chance_5": 0.00,
    "MEW": false,
    "promoA": false,
  },
  {
    "obtido": false,
    "code": "A1A052",
    "nome": "Centiskorch",
    "buster": "MEW",
    "raridade": "🔹🔹",
    "chance_1_3": 0.00,
    "chance_4": 2.571,
    "chance_5": 1.714,
    "MEW": false,
    "promoA": false,
  },
  {
    "obtido": false,
    "code": "A1A053",
    "nome": "Squirtle",
    "buster": "MEW",
    "raridade": "🔹",
    "chance_1_3": 2.000,
    "chance_4": 0.00,
    "chance_5": 0.00,
    "MEW": false,
    "promoA": false,
  },
  {
    "obtido": false,
    "code": "A1A054",
    "nome": "Wartortle",
    "buster": "MEW",
    "raridade": "🔹🔹",
    "chance_1_3": 0.00,
    "chance_4": 2.571,
    "chance_5": 1.714,
    "MEW": false,
    "promoA": false,
  },
  {
    "obtido": false,
    "code": "A1A055",
    "nome": "Blastoise",
    "buster": "MEW",
    "raridade": "🔹🔹🔹",
    "chance_1_3": 0.00,
    "chance_4": 0.357,
    "chance_5": 1.429,
    "MEW": false,
    "promoA": false,
  },
  {
    "obtido": false,
    "code": "A1A056",
    "nome": "Blastoise ex",
    "buster": "MEW",
    "raridade": "🔹🔹🔹🔹",
    "chance_1_3": 0.00,
    "chance_4": 0.333,
    "chance_5": 1.333,
    "MEW": false,
    "promoA": false,
  },
  {
    "obtido": false,
    "code": "A1A057",
    "nome": "Psyduck",
    "buster": "MEW",
    "raridade": "🔹",
    "chance_1_3": 2.000,
    "chance_4": 0.00,
    "chance_5": 0.00,
    "MEW": false,
    "promoA": false,
  },
  {
    "obtido": false,
    "code": "A1A058",
    "nome": "Golduck",
    "buster": "MEW",
    "raridade": "🔹🔹",
    "chance_1_3": 0.00,
    "chance_4": 2.571,
    "chance_5": 1.714,
    "MEW": false,
    "promoA": false,
  },
  {
    "obtido": false,
    "code": "A1A059",
    "nome": "Poliwag",
    "buster": "MEW",
    "raridade": "🔹",
    "chance_1_3": 2.000,
    "chance_4": 0.00,
    "chance_5": 0.00,
    "MEW": false,
    "promoA": false,
  },
  {
    "obtido": false,
    "code": "A1A060",
    "nome": "Poliwhirl",
    "buster": "MEW",
    "raridade": "🔹🔹",
    "chance_1_3": 0.00,
    "chance_4": 2.571,
    "chance_5": 1.714,
    "MEW": false,
    "promoA": false,
  },
  {
    "obtido": false,
    "code": "A1A061",
    "nome": "Poliwrath",
    "buster": "MEW",
    "raridade": "🔹🔹🔹",
    "chance_1_3": 0.00,
    "chance_4": 0.357,
    "chance_5": 1.429,
    "MEW": false,
    "promoA": false,
  },
  {
    "obtido": false,
    "code": "A1A062",
    "nome": "Tentacool",
    "buster": "MEW",
    "raridade": "🔹",
    "chance_1_3": 2.000,
    "chance_4": 0.00,
    "chance_5": 0.00,
    "MEW": false,
    "promoA": false,
  },
  {
    "obtido": false,
    "code": "A1A063",
    "nome": "Tentacruel",
    "buster": "MEW",
    "raridade": "🔹🔹",
    "chance_1_3": 0.00,
    "chance_4": 2.571,
    "chance_5": 1.714,
    "MEW": false,
    "promoA": false,
  },
  {
    "obtido": false,
    "code": "A1A064",
    "nome": "Seel",
    "buster": "MEW",
    "raridade": "🔹",
    "chance_1_3": 2.000,
    "chance_4": 0.00,
    "chance_5": 0.00,
    "MEW": false,
    "promoA": false,
  },
  {
    "obtido": false,
    "code": "A1A065",
    "nome": "Dewgong",
    "buster": "MEW",
    "raridade": "🔹🔹",
    "chance_1_3": 0.00,
    "chance_4": 2.571,
    "chance_5": 1.714,
    "MEW": false,
    "promoA": false,
  },
  {
    "obtido": false,
    "code": "A1A066",
    "nome": "Shellder",
    "buster": "MEW",
    "raridade": "🔹",
    "chance_1_3": 2.000,
    "chance_4": 0.00,
    "chance_5": 0.00,
    "MEW": false,
    "promoA": false,
  },
  {
    "obtido": false,
    "code": "A1A067",
    "nome": "Cloyster",
    "buster": "MEW",
    "raridade": "🔹🔹",
    "chance_1_3": 0.00,
    "chance_4": 2.571,
    "chance_5": 1.714,
    "MEW": false,
    "promoA": false,
  },
  {
    "obtido": false,
    "code": "A1A068",
    "nome": "Krabby",
    "buster": "MEW",
    "raridade": "🔹",
    "chance_1_3": 2.000,
    "chance_4": 0.00,
    "chance_5": 0.00,
    "MEW": false,
    "promoA": false,
  },
  {
    "obtido": false,
    "code": "A1A069",
    "nome": "Kingler",
    "buster": "MEW",
    "raridade": "🔹🔹",
    "chance_1_3": 0.00,
    "chance_4": 2.571,
    "chance_5": 1.714,
    "MEW": false,
    "promoA": false,
  },
  {
    "obtido": false,
    "code": "A1A070",
    "nome": "Horsea",
    "buster": "MEW",
    "raridade": "🔹",
    "chance_1_3": 2.000,
    "chance_4": 0.00,
    "chance_5": 0.00,
    "MEW": false,
    "promoA": false,
  },
  {
    "obtido": false,
    "code": "A1A071",
    "nome": "Seadra",
    "buster": "MEW",
    "raridade": "🔹🔹",
    "chance_1_3": 0.00,
    "chance_4": 2.571,
    "chance_5": 1.714,
    "MEW": false,
    "promoA": false,
  },
  {
    "obtido": false,
    "code": "A1A072",
    "nome": "Goldeen",
    "buster": "MEW",
    "raridade": "🔹",
    "chance_1_3": 2.000,
    "chance_4": 0.00,
    "chance_5": 0.00,
    "MEW": false,
    "promoA": false,
  },
  {
    "obtido": false,
    "code": "A1A073",
    "nome": "Seaking",
    "buster": "MEW",
    "raridade": "🔹",
    "chance_1_3": 2.000,
    "chance_4": 0.00,
    "chance_5": 0.00,
    "MEW": false,
    "promoA": false,
  },
  {
    "obtido": false,
    "code": "A1A074",
    "nome": "Staryu",
    "buster": "MEW",
    "raridade": "🔹",
    "chance_1_3": 2.000,
    "chance_4": 0.00,
    "chance_5": 0.00,
    "MEW": false,
    "promoA": false,
  },
  {
    "obtido": false,
    "code": "A1A075",
    "nome": "Starmie",
    "buster": "MEW",
    "raridade": "🔹🔹",
    "chance_1_3": 0.00,
    "chance_4": 2.571,
    "chance_5": 1.714,
    "MEW": false,
    "promoA": false,
  },
  {
    "obtido": false,
    "code": "A1A076",
    "nome": "Starmie ex",
    "buster": "MEW",
    "raridade": "🔹🔹🔹🔹",
    "chance_1_3": 0.00,
    "chance_4": 0.333,
    "chance_5": 1.333,
    "MEW": false,
    "promoA": false,
  },
  {
    "obtido": false,
    "code": "A1A077",
    "nome": "Magikarp",
    "buster": "MEW",
    "raridade": "🔹",
    "chance_1_3": 2.000,
    "chance_4": 0.00,
    "chance_5": 0.00,
    "MEW": false,
    "promoA": false,
  },
  {
    "obtido": false,
    "code": "A1A078",
    "nome": "Gyarados",
    "buster": "MEW",
    "raridade": "🔹🔹🔹",
    "chance_1_3": 0.00,
    "chance_4": 0.357,
    "chance_5": 1.429,
    "MEW": false,
    "promoA": false,
  },
  {
    "obtido": false,
    "code": "A1A079",
    "nome": "Lapras",
    "buster": "MEW",
    "raridade": "🔹🔹🔹",
    "chance_1_3": 0.00,
    "chance_4": 0.357,
    "chance_5": 1.429,
    "MEW": false,
    "promoA": false,
  },
  {
    "obtido": false,
    "code": "A1A080",
    "nome": "Vaporeon",
    "buster": "MEW",
    "raridade": "🔹🔹🔹",
    "chance_1_3": 0.00,
    "chance_4": 0.357,
    "chance_5": 1.429,
    "MEW": false,
    "promoA": false,
  },
  {
    "obtido": false,
    "code": "A1A081",
    "nome": "Omanyte",
    "buster": "MEW",
    "raridade": "🔹🔹",
    "chance_1_3": 0.00,
    "chance_4": 2.571,
    "chance_5": 1.714,
    "MEW": false,
    "promoA": false,
  },
  {
    "obtido": false,
    "code": "A1A082",
    "nome": "Omastar",
    "buster": "MEW",
    "raridade": "🔹🔹🔹",
    "chance_1_3": 0.00,
    "chance_4": 0.357,
    "chance_5": 1.429,
    "MEW": false,
    "promoA": false,
  },
  {
    "obtido": false,
    "code": "A1A083",
    "nome": "Articuno",
    "buster": "MEW",
    "raridade": "🔹🔹🔹",
    "chance_1_3": 0.00,
    "chance_4": 0.357,
    "chance_5": 1.429,
    "MEW": false,
    "promoA": false,
  },
  {
    "obtido": false,
    "code": "A1A084",
    "nome": "Articuno ex",
    "buster": "MEW",
    "raridade": "🔹🔹🔹🔹",
    "chance_1_3": 0.00,
    "chance_4": 0.333,
    "chance_5": 1.333,
    "MEW": false,
    "promoA": false,
  },
  {
    "obtido": false,
    "code": "A1A085",
    "nome": "Ducklett",
    "buster": "MEW",
    "raridade": "🔹",
    "chance_1_3": 2.000,
    "chance_4": 0.00,
    "chance_5": 0.00,
    "MEW": false,
    "promoA": false,
  },
  {
    "obtido": false,
    "code": "A1A086",
    "nome": "Swanna",
    "buster": "MEW",
    "raridade": "🔹🔹",
    "chance_1_3": 0.00,
    "chance_4": 2.571,
    "chance_5": 1.714,
    "MEW": false,
    "promoA": false,
  }
];
